### ISSUE TITLE
0.5.0 Release Guidelines

### ISSUE THREAD

**Issue by keithwhor** [keithwhor/nodal#10]
Things needed before release:

- :white_check_mark: Full method documentation
- :grey_question: Docs generator from documented methods (put on website)
- :grey_question: Step-by-step Instructional README, offload API docs to website
- :white_check_mark: Allow for hyphens in project names (don't just replace with underscore)
- :white_check_mark: Composer: Relationships through other Models (many:many)
- :white_check_mark: Composer: Where by joined fields
- :white_check_mark: Composer: Multiple joined children (children, pets in tests)
- :white_check_mark: Composer: groupBy, aliased columns, transformations = experimental (Removed)
- :white_check_mark: Composer: Ensure subsequent filters do not remove joined columns.
- :white_check_mark: Composer: Subsequent wheres by joined fields should work
- :white_check_mark: Model: Change `Model.joins(Parent)` to `Model.joinsTo(Parent)`. 
- :white_check_mark: Model: Change `Model#relationship` to `Model#include`

**Comment by keithwhor** [comment]
Want to figure out one last Composer issue...

```
Parent.query()
  .join('children')
  .filter({children__name: 'Hansel'})
  .end(() => {});
```

This currently would grab every parent with a child named "Hansel", and all of the children named "Hansel". The problem here becomes your `Parent` instances don't necessarily have all `Child` references in their associated `ModelArray` for the `'children'` relationship. Do we clarify this in the documentation, or do we refactor the query? I think I would prefer if the `Parent`s that were loaded had full `ModelArray`s. I might want to do something like;

```
Parent.query()
  .join('children')
  .filter({children__name: 'Jonathan'})
  .end((err, parents) => this.respond(err || parents));
```

In a controller, and list all of the children belonging to the parents. I'll have to think on this.

Furthermore, I'm not sure if `.limit()` makes sense anymore in the current implementation. You could get 30 rows back from a join `.limit(30)` but maybe only 5 models in your response, if there are a lot of children. Not very easy to reason about.

**Comment by keithwhor** [comment]
Composer has been refactored to accomplish what I talked about above. A query with a joined model will not limit what gets joined, only limits which initial parent objects are grabbed.

i.e.

```
Parent.query()
  .join('children')
  .filter({children__name: 'Jonathan'})
  .end((err, parents) => this.respond(err || parents));
```

The `parents` reference here will contain *all* children, even though we want to filter by children name = Jonathan. If you want to restrict what actually gets joined, perhaps a second parameter to the `.join()` call can be used. (TBD. Out of scope right now.)

**Comment by keithwhor** [comment]
Okay, so what I think I'm going to put on the roadmap is the following:

Canning many:many as a necessity for this release. I have to *actually* release, and that's a "nice-to-have." I marked it with poop, because I feel crappy about it. In reality if I don't finish it for this release, it'll be 0.5.1 easily... because it's a necessity for most applications.

Have an idea for how I want it to work --- Models should be smart enough on their own to figure out if they can ever join with another model (or join alias). They should do a simple graph search across dependencies (through the `Model.prototype._joins` object). In order to join them in I'd just have to do a LEFT JOIN chain. When querying by these objects as filters, I'd need to do an INNER JOIN chain.

There might be complexity I'm missing. In the meantime I have to finish some last bugs and then throw together the website / documentation.

**Comment by keithwhor** [comment]
Also want to queue up Rails-style "plucking". Instead of `Composer#end()` have something like `Composer#pluck` which you provide an interface to (`Model#toObject()` style) and a callback. Doesn't fetch models. Just returns the plain-old objects matching the schema you provided.

**Comment by keithwhor** [comment]
Removing the requirement order by joined fields in the Composer. Too much complexity right now. The Composer joins in fields last, always, by design.

**Comment by keithwhor** [comment]
I released anyway and ignored full docs. Coming soon though ;).

**Comment by chesstrian** [comment]
Great, will start using it :smile:
