### ISSUE TITLE
id parameter not taken into account for distinguishing  index and show methods

### ISSUE THREAD

**Issue by fredrb** [keithwhor/nodal#114]
Even when using `id` parameter the router calls `index()` method other then `show()`.

**Comment by fredrb** [comment]
Please check if this is the expected behaviour and the referenced PR is sufficient for fixing this. 
I tested with the scenario that was failing for me and the router is calling the expected method now.

**Comment by keithwhor** [comment]
commented on the PR, but;

id to trigger `show()` isn't a query parameter, its after the last forward slash in the url.
i.e. if your route is `/^\/airplanes\/?/`, and you hit it with `/airplanes/1`, id is 1.

I'll leave this open because I'll probably change this behavior moving forward.

**Comment by fredrb** [comment]
@keithwhor what are you planning to change? `show()` being called when id is passed or the way you pass an id in URL?

**Comment by keithwhor** [comment]
The way we pass ids in the url. I have to think about it. Probably capturing groups in regex.

**Comment by keithwhor** [comment]
Going to put this on the workload for tomorrow.

**Comment by keithwhor** [comment]
Routes now accept plain string, and '/api/v1/my_objects/:id' will route to the appropriate controller, and provide a `this.params.route.id` object for the id (and trigger the `show` endpoint).

Thanks for pointing this out. :)

**Comment by keithwhor** [comment]
Oh, link, https://github.com/keithwhor/nodal/commit/153833da4bc21d20d7d861040209419da5154fbd

**Comment by pewh** [comment]
I face this issue again on nodal latest version (0.7.5).
`api/v1/users/1` triggers `index()` instead of `show()`.
I've inspect `this.params.route` on `index()` and it returns `{ id: undefined }`

**Comment by pewh** [comment]
Fixed on 0.7.6. Good work @keithwhor  :+1:
