### ISSUE TITLE
Ditch DoT.js

### ISSUE THREAD

**Issue by niallobrien** [keithwhor/nodal#119]
Hi, just wondering what you think about ditching DoT.js? It hasn't been updated in over a year and has quite a few unopened issues.

Personally, I think Jade or Nunjucks would be a great choice.

What are your thoughts?

**Comment by keithwhor** [comment]
Not really interested at this point. Ton of overhead for a problem Nodal isn't focused on solving. Our integration with doT does what it need to do (partial support, child templates, etc.) and it's fast.

**Comment by keithwhor** [comment]
Apologies if I was a little abrupt there --- to clarify, I appreciate the insight, we'll be generating a lot more tooling focused around front-end solutions in the coming weeks and you'll see why having an ultra-expressive templating language isn't a huge priority right now. :smile:

**Comment by niallobrien** [comment]
Cool, I see most projects simply use something like [Consolidate.js](https://github.com/tj/consolidate.js/) which allows users to use whatever templating language/pre-processor they prefer. I think supporting a modern templating language that's still maintained (DoT.js looks dead) would be a sound investment. Not everyone are building single page apps. ;) Thanks in advance.
