### ISSUE TITLE
Missings docs

### ISSUE THREAD

**Issue by mastermind1981** [keithwhor/nodal#12]
@keithwhor good job, I like the simplicity of Nodal, so keep the focus on it. There is no doc on the nodaljs.com and I think this should be fixed very quickly.

**Comment by keithwhor** [comment]
This weekend. I promise. :)

**Comment by mastermind1981** [comment]
We are Monday the weekend is too far,  you should not be lazy :-)  ... Nodal got the attention, now you should keep that attention ... I am not talking on my behalf only ... there is a lot lazy people if there is no doc they will turn back ... roll up your sleeve :-)

**Comment by keithwhor** [comment]
I'll let you know as soon as they're ready. Thanks for supporting the project!

**Comment by fuzzthink** [comment]
Hope you will consider using a good doc tools while you're working on the doc. The one on site is very poor on usability.  One needs to click to expand and it jumps to top of the page.

**Comment by keithwhor** [comment]
Going to close this for now - but certainly, we need to spend more time thinking about the auto-generated docs. I can generate the AST as JSON so we can probably write our own wrapper to format into a docs page.
