### ISSUE TITLE
odd self invoking functions in controllers?

### ISSUE THREAD

**Issue by stalniy** [keithwhor/nodal#120]
For example here: https://github.com/keithwhor/nodal/blob/master/src/app/controllers/index_controller.js

Each nodejs module has its own scope of variables and only stuff in `exports` is exposed and everything what is assigned to `global` object.

So, don't see reason in complicating controllers with self invoking function.
```js
module.exports = class IndexController extends Nodal.Controller {
  ....
};
``

**Comment by keithwhor** [comment]
https://github.com/keithwhor/nodal/issues/110
https://github.com/keithwhor/nodal/issues/20
