### ISSUE TITLE
this.addColumn is adding empty properties object but not on initial table create

### ISSUE THREAD

**Issue by combsco** [keithwhor/nodal#124]
When you **create a new model** and specifiy your columns from the command line these columns are not getting the empty properties field treatment in schema.js

**Generating a new model**
```nodal g:model Calls firstName:string lastName:string phone:string agency:string method:string user_id:int```

**2016012200571535__create_call.js**
```
    up() {

      return [
        this.createTable("calls", [{"name":"first_name","type":"string"},{"name":"last_name","type":"string"},{"name":"phone","type":"string"},{"name":"agency","type":"string"},{"name":"method","type":"string"},{"name":"user_id","type":"int"}])
      ];

    }
```

**schema.js** - all columns with no properties.
```
    "Call": {

      "table": "calls",

      "columns": [
        {"name": "id", "type": "serial", "properties": {"nullable":false,"primary_key":true,"auto_increment":true}},
        {"name": "first_name", "type": "string"},
        {"name": "last_name", "type": "string"},
        {"name": "phone", "type": "string"},
        {"name": "agency", "type": "string"},
        {"name": "method", "type": "string"},
        {"name": "user_id", "type": "int"},
        {"name": "created_at", "type": "datetime"},
        {"name": "updated_at", "type": "datetime"}
      ]

    }
```

Now if we add a new column to calls model ```nodal g:migration AddColumnsToCalls``` and we use ```this.addColumn("calls", "email", "string")``` ... after this is migrated the changed schema:

**schema.js**
```
    "Call": {

      "table": "calls",

      "columns": [
        {"name": "id", "type": "serial", "properties": {"nullable":false,"primary_key":true,"auto_increment":true}},
        {"name": "first_name", "type": "string"},
        {"name": "last_name", "type": "string"},
        {"name": "phone", "type": "string"},
        {"name": "agency", "type": "string"},
        {"name": "method", "type": "string"},
        {"name": "user_id", "type": "int"},
        {"name": "created_at", "type": "datetime"},
        {"name": "updated_at", "type": "datetime"},
        {"name": "email", "type": "string", "properties": {}}
      ]

    }
```

---------
The code causing the issue is ... *core/required/db/migration.js*
```
addColumn(table, column, type, properties) {
    properties = properties || {};
```

My thought wouldn't you want the initial table create to also have empty properties for all columns?

**Comment by intabulas** [comment]
My opinion is the same, for consistency we should either add `{}` for both or drop it on both. Prefer adding it as it help users grok that things like unique need to be inside properties

**Comment by keithwhor** [comment]
Alright. We can queue this up (always showing it).

**Comment by intabulas** [comment]
@keithwhor done in #130
