### ISSUE TITLE
Retrieving Bearer token from alternative locations than the query string

### ISSUE THREAD

**Issue by combsco** [keithwhor/nodal#125]
For most APIs i've had the opportunity to consume they require the API key and/or access token to be passed in the header ```Authorization: Bearer [token]```. I noticed Nodals default implementation is to use the query string ?access_token=

I think providing an alternative way to get the access_token would be great. This would keep your query string clean from containing that token.

```
GET /resource HTTP/1.1
Host: server.example.com
Authorization: Bearer vF9dft4qmT
```

Add to the **verify** function in _models/access_token.js_
```
...
      let token_type;
      let access_token;

      // Authorization: Bearer [access_token]
      if (params.headers && params.headers.authorization) {
        let pieces = params.headers.authorization.split(' ');
        if (pieces.length === 2 && /^Bearer$/i.test(pieces[0])) {
          token_type = 'bearer';
          access_token = pieces[1];
        } else {
          return callback(new Error('Format is Authorization: Bearer [access_token]'));
        }
      // ?access_token=[access_token]
      } else if (params.query.access_token) {
        token_type = 'bearer';
        access_token = params.query.access_token;
      }
...
```

Also since we are storing the *token type* in the database when we created this token... comparing it in the query might help too.

```
...
      this.query()
        .join('user')
        .where({
          token_type: token_type,
          access_token: access_token,
...
```

##### IEFT Recommendation
>    Don't pass bearer tokens in page URLs:  Bearer tokens SHOULD NOT be
      passed in page URLs (for example as query string parameters).
      Instead, bearer tokens SHOULD be passed in HTTP message headers or
      message bodies for which confidentiality measures are taken.
      Browsers, web servers, and other software may not adequately
      secure URLs in the browser history, web server logs, and other
      data structures.  If bearer tokens are passed in page URLs,
      attackers might be able to steal them from the history data, logs,
      or other unsecured locations.

**Comment by keithwhor** [comment]
Alright. We'll implement this fix immediately. Have to change a few things to be compatible.

**Comment by combsco** [comment]
It's just a *suggestion* on the access_tokens not necessarily an issue.

**Comment by keithwhor** [comment]
Yeah but it's a damn good suggestion. :+1:

**Comment by niallobrien** [comment]
Great stuff guys! :)

**Comment by ummjackson** [comment]
ETA on this reaching master?

**Comment by intabulas** [comment]
PR #177 was created to do this. Access tokens are automatically extracted from query params or authorization headers and added (by router during dispatch) as an `auth` object on the params object passed to the controllers (or access_token#verify)

**Comment by intabulas** [comment]
@keithwhor  we can close this now
