### ISSUE TITLE
Postgres data type checking in generator?

### ISSUE THREAD

**Issue by alexanderbanks** [keithwhor/nodal#138]
```
nodal g:model SomeModel name:sttring
```

Running this command, there are no errors returned and the console output is all successful, but attempting to work with the model via a controller is always unsuccessful. I understand this could just be considered user error and not a bug, but I figured I'd point it out either way.

**Comment by keithwhor** [comment]
We'll make verbose errors here. Thanks for pointing it out. :)

**Comment by justinobney** [comment]
Having some examples of how specific/complex you can get with the model generator would be great.

**Comment by intabulas** [comment]
PR #148 will now throw an error in any column type isn't supported by the adapater
