### ISSUE TITLE
ELIFECYCLE error when creating user model.

### ISSUE THREAD

**Issue by PaulMaas** [keithwhor/nodal#150]
When running
```
nodal g:model --user
```
It breaks my nodal project and can't be started again. Here is my npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ao-admin@0.0.0~prestart: ao-admin@0.0.0
6 silly lifecycle ao-admin@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle ao-admin@0.0.0~start: ao-admin@0.0.0
8 verbose lifecycle ao-admin@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ao-admin@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle ao-admin@0.0.0~start: CWD: /usr/src/app
11 silly lifecycle ao-admin@0.0.0~start: Args: [ '-c', 'node server.js --harmony' ]
12 silly lifecycle ao-admin@0.0.0~start: Returned: code: 7  signal: null
13 info lifecycle ao-admin@0.0.0~start: Failed to exec start script
14 verbose stack Error: ao-admin@0.0.0 start: `node server.js --harmony`
14 verbose stack Exit status 7
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ao-admin@0.0.0
16 verbose cwd /usr/src/app
17 error Linux 4.1.13-boot2docker
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error ao-admin@0.0.0 start: `node server.js --harmony`
22 error Exit status 7
23 error Failed at the ao-admin@0.0.0 start script 'node server.js --harmony'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ao-admin package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js --harmony
23 error You can get their info via:
23 error     npm owner ls ao-admin
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Node version 5.5.0.
Npm version 3.3.12
Nodal version 0.6.0

**Comment by keithwhor** [comment]
Can you try with node 4.2.4?

**Comment by PaulMaas** [comment]
I did, that was the first node version I tried.

I found the problem line (44): ```User.setSchema(Nodal.my.Schema.models.User);``` in app/models/user.js. When I commented this out I was able to get the server running again and execute the following lines to create the controller and perform the migration. After the migration I uncommented the line and everything works.

It seems that line 44 requires db/schema.json to have the data that it doesn't have until the migration has run. Re-ordering this stuff a little would solve this problem. I believe the schema (in db and codebase) should be there before it is 'used'... Let me know what you think... I could write a PR for this tomorrow.

**Comment by keithwhor** [comment]
I'm not able to recreate this error. `nodal g:model --user` works fine for me on new projects. You just need to make sure you run the migration before you run your server. The issue here is probably just that the Error isn't very explicit. :) We can fix that.

**Comment by PaulMaas** [comment]
Yes, you are right. However, if you're running Nodal and PostgreSQL in docker containers, then you'll have to run the commands (particularly the db ones) inside of the docker shell. Once the model is created, the docker container running nodal breaks down and can't be restarted. So you're 'blocked' from running the migration. The only fix is to comment/remove the line that references the (not yet existing) schema.

Like I said before, I think it's more logical to create the schema at the time the model that references it is created. The migration is already being created at that time anyway... Is there a reason we can't create the schema at the same time? It's more atomic that way... Having a 'broken project' in between commands has kind of a bad smell to it imho :).

Added benefit of the suggested change is that, with the suggested addition from @michaelmior (Dockerfile and docker-compose.yml) you can advertise support for Docker :D.

**Comment by michaelmior** [comment]
@PaulMaas I'll try to check this out over the weekend.

**Comment by keithwhor** [comment]
Doesn't make sense to have your g:migration command generate your schema. Your schema is a representation of the current state of your database.

Having a "broken project" in between commands is fine. The issue here is the error is not verbose ("please run db:migrate").

**Comment by michaelmior** [comment]
After reading this closely, looks like it has nothing to with Docker, right @keithwhor?

**Comment by PaulMaas** [comment]
@keithwhor my suggestion is to add the schema when g:model is run instead of when db:migrate is (as it is now). When the model is created it has a broken reference to the schema that isn't fixed until db:migrate is run (as you said). 

@michaelmior This does cause problems with docker because docker runs one command per container. In this case, nodal,  which shuts down and can't be restarted until the broken reference to the schema is fixed. The db:* commands (specifically) have to be run from this container to work. So you can't run db:migrate to fix the issue... essentially, you're caught between a rock and a hard place unless you know to temporarily comment out the schema reference in your new model.

Just try it out with a brand new project... with the docker setup michael suggested in #37, try to go through the steps shown on the index page of the new project... you'll see what I'm talking about...

Sorry about the lengthy post. I'm just trying to make sure we're all in the same page. 

Thanks, 

PVDM

**Comment by keithwhor** [comment]
You can run db:bootstrap which does db:create, db:prepare, db:migrate and db:seed. No intention of changing this. Closing the issue. Will address the actual error messages (more explicit) in next release. :+1: Thanks for brining this to our attention.
