### ISSUE TITLE
Tweet-User join brings back all tweets

### ISSUE THREAD

**Issue by jgoode** [keithwhor/nodal#152]
Following along with the tutorial video, part 2. When I add in the join to the user table, it is bringing back all tweets. [GET: http://localhost:3000/v1/tweets?user_username=john]

{
  "meta": {
    "total": 3,
    "count": 3,
    "offset": 0,
    "error": null
  },
  "data": [
    {
      "id": 3,
      "user_id": 1,
      "body": "Hello world",
      "created_at": "2016-01-31T14:07:20.182Z",
      "updated_at": "2016-01-31T14:07:20.183Z",
      "user": {
        "id": 1,
        "email": "johnhgoode@gmail.com",
        "password": "",
        "username": "john",
        "created_at": "2016-01-31T13:59:44.926Z",
        "updated_at": "2016-01-31T13:59:44.997Z"
      }
    },
    {
      "id": 4,
      "user_id": 1,
      "body": "Hello John",
      "created_at": "2016-01-31T14:10:06.128Z",
      "updated_at": "2016-01-31T14:10:06.129Z",
      "user": {
        "id": 1,
        "email": "johnhgoode@gmail.com",
        "password": "",
        "username": "john",
        "created_at": "2016-01-31T13:59:44.926Z",
        "updated_at": "2016-01-31T13:59:44.997Z"
      }
    },
    {
      "id": 5,
      "user_id": 2,
      "body": "Hello Dave",
      "created_at": "2016-01-31T14:10:24.321Z",
      "updated_at": "2016-01-31T14:10:24.321Z",
      "user": {
        "id": null,
        "email": null,
        "password": null,
        "username": null,
        "created_at": null,
        "updated_at": null
      }
    }
  ]
}

**Comment by keithwhor** [comment]
Can you show me the `index()` contents for the controller? (Wrap in backticks to format as code)

**Comment by keithwhor** [comment]
Ah. I see the issue. If you're passing `this.params.query` to `.where()` in your controller, `user__username` must have a **double underscore**.

**Comment by jgoode** [comment]
Thanks. That did the trick!

BTW, really am digging Nodal JS.

**Comment by keithwhor** [comment]
:+1: No problem! Thanks! You actually helped me identify another bug. :)
