### ISSUE TITLE
Way to apply function to values in toResource?

### ISSUE THREAD

**Issue by paulhart** [keithwhor/nodal#153]
Hi there,

I would like to be able to modify the values that are passed back to the visitor as a result of an API call, but without storing these variations to the database. From what I can tell, this would require me to do one of the following:

* Loop through the returned values and apply my modifications;
* Pass function references as part of the array that is the respond() method's second parameter. Perhaps if a member of that array is itself an array, it would identify this? The same style could also be used on the joined arrays.

For instance, something like the following (no guarantees on code validity):

```
index() {
  Tweet.query()
    .join('user')
    .where(this.params.query)
    .end((err, models) => {
      this.respond(err || models, ['id', ['body', Tweet.shoutyBody], 'created_at', {user: ['id', 'username', 'created_at']}]);
    });
}
static shoutyBody(v) {
  return v.toUpperCase() + '!!111!!One!';
}

```

**Comment by keithwhor** [comment]
You can actually do this with calculated fields.

In `models/tweet.js`...

```
Tweet.calculates('shoutBody', (body) => body.toUpperCase() + '!!111!!One!');
```

**Comment by keithwhor** [comment]
Then you have to make sure `shoutyBody` is in your interface

**Comment by paulhart** [comment]
What happens if I try and override the original value? i.e.
```
Tweet.calculates('body', (body) => body.toUpperCase() + '!!111!!One!');
```

**Comment by keithwhor** [comment]
Infinite loop. Don't do that.
