### ISSUE TITLE
Support/use Sequelize

### ISSUE THREAD

**Issue by talyssonoc** [keithwhor/nodal#157]
Do you guys plan to use Sequelize for the ORM? I guess it would be easier do use and setup than the current solution, it already supports migrations, seeds...

Also, it would still have compatibility with the easiness of using Rails, since in Rails you still have to install `pg` gem when using PostgreSQL, for example, similar to using `pg` package with Sequelize.

**Comment by keithwhor** [comment]
Not at present, the ORM is pretty mature as-is. Thanks for asking, though.
