### ISSUE TITLE
undefined error when nodal new

### ISSUE THREAD

**Issue by colinshen** [keithwhor/nodal#166]
windows 10

Copying Nodal directory structure and files...

Copying cli...
Error: undefined
Help: Type `nodal help` to get more information about what Nodal can do for you.

**Comment by keithwhor** [comment]
Can you check out `nodal@0.7.5-rc1` on NPM (or directly link from the repo) and tell me the error you're getting? I think there's an issue with `fs.copy` from `fs-extra` but it's throwing a string error.

Let me know, don't have a VM running right now so this might be faster.

**Comment by abossard** [comment]
Hi, I have the same problem with Windows 10 and nodal@0.7.5-rc1

    andre@ANDRE-PC C:\Users\andre\Documents\GitHub
    $ nodal new

    Welcome to Nodal! v0.7.5-rc1

    ? Name autodous
    ? Author Homer Simpson
    Creating directory "autodous"...
    
    Copying Nodal directory structure and files...

    Copying cli...
    Error: undefined
    Help: Type `nodal help` to get more information about what Nodal can do for you.

**Comment by keithwhor** [comment]
Alright. Spinning up a VM. Will get back to you soon.

**Comment by abossard** [comment]
It doesn't give the error, but in the project directory, the nodal project is not preinstalled.

**Comment by abossard** [comment]
I updated and fixed the pull request. It works now, please have a look.
