### ISSUE TITLE
Allow for new fields on existing models via the commandline

### ISSUE THREAD

**Issue by bmann** [keithwhor/nodal#168]
Right now, you can create new migrations (e.g. to add new fields) using this command:
``nodal g:migration ExistingModel``

And then you manually edit the new migration to add fields / columns:
``this.addColumn("location", "city", "string")``

It would be great if you could do this on the commandline directly, eg. something like:
``nodal g:migration ExistingModel newField1:int newField2:string``

**Comment by intabulas** [comment]
maybe stay consistent with model refs like when generating a controller

`nodal g:migration AddNewColumnsToBlah --for:Blah  newcol:type`

**Comment by keithwhor** [comment]
Gonna try to tack this on today.

**Comment by keithwhor** [comment]
Added in https://github.com/keithwhor/nodal/commit/02c80b44c128db89b685e6c1b67c4cff046db59c
