### ISSUE TITLE
Better errors for nodal db:seed

### ISSUE THREAD

**Issue by bmann** [keithwhor/nodal#169]
If your JSON is malformed, you get ``Error: Could not seed, no seed found in "./config/seed.json"`` -- would be great to have a message saying that your JSON is wrong.

**Comment by intabulas** [comment]
I think simply changing the error message here will suffice since Config does it all in a try catch.. @keithwhor any objections?

**Comment by keithwhor** [comment]
No objections. Will look into it.

**Comment by keithwhor** [comment]
https://github.com/keithwhor/nodal/commit/cd0df92d72b8079e26059f93b656cc63a5c06236
