### ISSUE TITLE
Nodal 0.7 doesn't capture POST data

### ISSUE THREAD

**Issue by pewh** [keithwhor/nodal#171]
Hi everybody. I've problem on sending POST request via x-www-form-urlencoded. I've fill some data but `this.params.body` doesn't capture any data. Is it a bug from nodal 0.7? Or is it caused by CSP?

Note:
I've test on postman & curl. Also doing a debugger seems `this.params.body` return StrongParams with empty value

**Comment by bAmpT** [comment]
Only JSON data works for me and they changed the way to access the header data as well. 
this._requestHeader 
( before it was this.params.header )

**Comment by pewh** [comment]
Hi @bAmpT
Thanks for your quick response :)
Can you give me some guide how to make it work. I still can't figure out how to solve my issue.
Have you modified controller so it can work with JSON data?
In my generated controller, I get this on `create()` method.

```
User. create(this. params. body, (err, model) ...
```

I also trying `{ "email": "foo@bar.com" }`, but nothing to be captured.

this._requestedHeader also return undefined

**Comment by bAmpT** [comment]
I haven't modified it, but for me x-www-form-urlencoded didn't work, so I used JSON and it worked. But it clearly seems to have a problem!

**Comment by pewh** [comment]
If I may know, what's the nodal version you used? Have you set HTTP Headers on each request?

**Comment by pewh** [comment]
Aha!
Finally I can make POST request to nodal. I solve my problem by using json data and then set `Content-Type: application/json`.
Thanks @bAmpT for your guide.
Anyway the docs need to be updated to avoid confusion on using x-www-form-urlencoded
