### ISSUE TITLE
Alter createIndex to use Array of Field data ala createTable

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#172]
Right now (0.7.x) `createIndex()` is simple function that takes a single Column.  You can not create, as one example, a unique index using `createIndex()`. The only way to get a unique index currently is to use the `:unique` modifier when creating a model or adding a column to a model. The only negative with this (and not a bug) is the index wont show in schema.json

I propose we adjust `createIndex` to take array of field data like `createTable` to allow for more complex index construction. 

Some examples:
* Unique Index
* Multi-Column Index
* GIS index's ( ex: box() )

**Comment by keithwhor** [comment]
Can we just add another argument to createIndex for this purpose?
