### ISSUE TITLE
Need one to many relationships example

### ISSUE THREAD

**Issue by pewh** [keithwhor/nodal#174]
Hello. I cannot figure out how to do one-to-many relationship. It is actually a question rather than issue.

I have two tables: `Product` and `Category`. `Product` has many `Category`. So what I've done are:

- Create `Product` table with:
```
        this.createTable("products", [{
          "name": "name",
          "type": "string"
        }, {
          "name": "description",
          "type": "string"
        }])
```

- Create `Category` table with:
```
        this.createTable("categories", [{
          "name": "name",
          "type": "string"
        }, {
          "name": "stock",
          "type": "int"
        }, {
          "name": "productId",
          "type": "int"
        }])
```

- Modify `index()` method on `ProductsController`:
```
      Product.query()
        .join('category')
        .where(this.params.query)
        .end((err, models) => {

          this.respond(err || models);

        });
    }
```

- Modify `Category` model by adding:
```
  const Product = Nodal.require('app/models/product.js');
  Category.joinsTo(Product, { via: 'productId', multiple: true });
```

I got an error `Error: Model Product does not have relationship "category".`.
I'm sure there are things I miss, but I can't figure out.

**Comment by pewh** [comment]
Solved. Thanks @keithwhor for the guide.

**Comment by js62789** [comment]
@keithwhor @pewh Is there a way to solve this using `Nodal.Model`? Or is it maybe on the roadmap? I'm trying to attach children in the same fashion and would like to know the correct method.

**Comment by ncksllvn** [comment]
I think this:

`Model.joinsTo(AnotherModel, { multiple: true });`
