### ISSUE TITLE
Update introductory videos for Nodal 0.7 or stable release

### ISSUE THREAD

**Issue by combsco** [keithwhor/nodal#175]
Intro videos are most likely out of date with the changes in Nodal 0.7 ... commonly the JSON data vs X-WWW-FORM-URLENCODED data on a POST request.

There could be others...

**Comment by bAmpT** [comment]
I this that JSON post data problem is fixed by now, update to 0.7.6 and it will work again..

**Comment by bAmpT** [comment]
But it would be nice to have the videos updated or continued!

**Comment by keithwhor** [comment]
Gonna close this. Not part of the repo. Will record new videos when I have time.
