### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by abossard** [keithwhor/nodal#176]
Hi Keith,

Thanks for all the effort you put into nodal.js. I'm looking for ways to contribute, but I'm struggling with just having a setup, where I can use the checkout out nodal project as the actual nodal command.

So that I don't have to work in the global node_modules installation, but in the project directory. 

How do you have set it up on your side?

**Comment by keithwhor** [comment]
Great. We need to get this up, you're right.

You can use + develop with nodal locally by cloning the repo to `~/nodal` and then...

```
$ cd ~
$ npm link
```

This will hook up your `nodal` command globally to the repository you have in `~/nodal`.

For testing a project with your development version, once you've performed `nodal new` to start a project, enter the project directory and type `npm link nodal`. This will link `~/nodal` to `node_modules/nodal` for the project you're on.

**Comment by abossard** [comment]
Thank you very much!

**Comment by bmann** [comment]
Stuck it in the wiki --> https://github.com/keithwhor/nodal/wiki/Contribution-Guide

@keithwhor unless you tell me to put this elsewhere, I'll keep stashing stuff in the wiki.

**Comment by abossard** [comment]
I think the wiki is a great place for it, as it doesn't require PR for every change :-)
