### ISSUE TITLE
GraphQL not work on some deep level query

### ISSUE THREAD

**Issue by pewh** [keithwhor/nodal#178]
It seems nodal cannot handle deep query on some situations. For example, I have 4 tables, which are: `Order`, `OrderDetail`, `Product`, `Image`, and `Category`.
A `Order` has many `OrderDetail`s.
A `OrderDetail` has one `Product` and one `Category.
A `Product` has one `Image.
So what I've done is querying `Order` model like this:

```
        order {
          id,
          total_price,
          status,
          user_id,
          details {
            id,
            purchasing_price,
            selling_price,
            quantity,
            category, // <-- delete this line make it work
            product {
              name,
              description,
              image {
                name,
                url
              }
            }
          }
        }
```

I got an error message `"table name \"details\" specified more than once"`. But when I delete `category` property (look at below), or change `category` into `category_id`, it's work. **Or** if I delete `product` property and don't delete `category`, it's work. It seems I can only querying either `category` or `product` on `details`, but not both.

And one more thing, I have create graphql query for `OrderDetail` model like this:
```
          order_detail {
            id,
            purchasing_price,
            selling_price,
            quantity,
            category,
            product {
              name,
              description,
              image {
                name,
                url
              }
            }
          }
```
and it's work.

The conclusion is: I can make it work on querying `OrderDetail`, but failed on `Order` model.

I have post [my sample repo](https://github.com/pewh/nodal-graphql-sample). You can do `nodal db:bootstrap` and test api by `http://localhost:3000/v1/orders` to reproduce my problem. Thanks

**Comment by keithwhor** [comment]
Fixed in https://github.com/keithwhor/nodal/commit/2a442b94b42314eba76154e83845d441592d5079

Will deploy to npm soon.
