### ISSUE TITLE
Media == Medium

### ISSUE THREAD

**Issue by JesseScott** [keithwhor/nodal#179]
First, diving into Nodal now, and it's really exciting!
But I just ran into a weird error:

So, I was creating a new model '_Media_'... and it got created as '_Medium_'

```
jscott@Jesses-Mac-mini:~/Documents/_PERSONAL/Code/github/TheArtBox.Server/tab$ nodal g:model Media id:int title:string subtitle:string body:string featured:Boolean
Create: ./app/models/medium.js
Create: ./db/migrations/2016021706395863__create_medium.js
```

**Comment by JesseScott** [comment]
Might be related to #164

**Comment by keithwhor** [comment]
Medium is the correct singular form of Media, so this behavior is expected. :)

**Comment by JesseScott** [comment]
oh... never even caught that. of course!
