### ISSUE TITLE
Won't scheduled tasks block your incoming API requests?

### ISSUE THREAD

**Issue by shawn-simon** [keithwhor/nodal#18]
I'm trying to understand the design patterns here, why would you run scheduled tasks on your API server?

**Comment by keithwhor** [comment]
You can, but you don't really need to. You can run your scheduler(s) in a worker, no problem. If a scheduled task was highly synchronous it could, theoretically, block incoming requests.

At Storefront we had a scheduler running on an app server just to refetch an in-memory graph from Redis. Very fast, the heavy lifting (generation of the graph) was offloaded to a Nodal worker.
