### ISSUE TITLE
.join does not work

### ISSUE THREAD

**Issue by kulakowka** [keithwhor/nodal#180]
I have been studying your video: https://www.youtube.com/watch?v=cQW4tgQsV_I 

And when i try `.join('user')` in Tweets controller like this: 
```javascript
Tweet.query()
  .join('user')
  .where(this.params.query)
  .end((err, models) => {
    this.respond(err || models);
  });
```

Server response for `http://localhost:3000/v1/tweets?user_id__not_null` looks like this:
```json
{
  "meta": {
    "total": 1,
    "count": 1,
    "offset": 0,
    "error": null
  },
  "data": [
    {
      "id": 8,
      "user_id": 1,
      "body": "First tweet from kulakowka",
      "created_at": "2016-02-17T23:55:17.526Z",
      "updated_at": "2016-02-17T23:55:17.527Z"
    }
  ]
}
```
The user is not joined. 

My tweet model looks like:
```javascript
module.exports = (function() {

  'use strict';

  const Nodal = require('nodal');
  const User = Nodal.require('app/models/user.js');

  class Tweet extends Nodal.Model {}

  Tweet.setDatabase(Nodal.require('db/main.js'));
  Tweet.setSchema(Nodal.my.Schema.models.Tweet);

  Tweet.joinsTo(User, {multiple: true});

  Tweet.validates('body', 'must be at least 5 characters', v => v && v.length >= 5)

  return Tweet;

})();
```

Tell me where I go wrong?

**Comment by kulakowka** [comment]
I have one user:

`GET http://localhost:3000/v1/users`

```json
{
  "meta": {
    "total": 1,
    "count": 1,
    "offset": 0,
    "error": null
  },
  "data": [
    {
      "id": 1,
      "username": "kulakowka",
      "email": "kulakowka@gmail.com",
      "created_at": "2016-02-17T23:46:36.720Z"
    }
  ]
}
```

**Comment by keithwhor** [comment]
Which version of Nodal are you using?

**Comment by kulakowka** [comment]
Oh, when i changed index action for Tweets controller to:
```javascript
Tweet.query()
        .join('user')
        .where(this.params.query)
        .end((err, models) => {
          this.respond(err || models, ['id', 'body', 'created_at', {user: ['id', 'username', 'created_at']}]);
        });
```
It worked!

Now, server response looked like:
```json
{
  "meta": {
    "total": 1,
    "count": 1,
    "offset": 0,
    "error": null
  },
  "data": [
    {
      "id": 8,
      "body": "First tweet from kulakowka",
      "created_at": "2016-02-17T23:55:17.526Z",
      "user": {
        "id": 1,
        "username": "kulakowka",
        "created_at": "2016-02-17T23:46:36.720Z"
      }
    }
  ]
}
```

Obviously the video is out of date?

**Comment by kulakowka** [comment]
i used last version:
```
Nodal Version: 0.7.7
```

**Comment by keithwhor** [comment]
Ah.

The issue here is that Nodal, by default, doesn't include joined models in the output. This is to prevent circular reference problems in relation to GraphQL.

I'm glad you found the issue, I hadn't made note of these changes.

**Comment by kulakowka** [comment]
Here is my code of the application: https://github.com/kulakowka/nodal-experiment/commit/1e3b6a9b6ad07ad216374ca8eebd68e97614c2fa#diff-0103adb22f8d821417e409ba448e9d8e if necessary. 

Thanks for the quick response. I really like nodal.
I will continue to explore it. %)

**Comment by GumptionWare** [comment]
Thanks for entering this issue. I had the same problem, and this did the trick.
