### ISSUE TITLE
add .gitignore to application generator

### ISSUE THREAD

**Issue by kulakowka** [keithwhor/nodal#181]
I have created a new application using the command-line utility.

And when I executed the command `git init`, then `git status`. I have not seen `.gitignore` file.

```bash
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.nodal
	.npmignore
	.travis.yml
	Procfile
	README.md
	app/
	cluster.js
	config/
	db/
	initializers/
	middleware/
	node_modules/
	package.json
	renderware/
	schedulers/
	static/
	tasks/
	test/
	worker.js
```

Maybe it makes sense to add `.gitignore` file in the application generator? In order to `node_modules` folder was not included in the repository.

**Comment by keithwhor** [comment]
Not interested in doing this yet. Good suggestion though, thank you. :+1:
