### ISSUE TITLE
Postgres Adapter Filter Improvements

### ISSUE THREAD

**Issue by PaulMaas** [keithwhor/nodal#183]
The postgres.js adapter needs a couple enhancements.

Case insensitive equals: ```iequals``` or ```iexact``` (per Django)
Update ```is``` and ```not``` to support booleans.

When I have time, I will create a PR for these.

Comments and additions are welcome...

**Comment by keithwhor** [comment]
Should support boolean, need to compare to string 't' / 'f'.

**Comment by keithwhor** [comment]
Actually, case insensitive equals is supported too. Use `ilike`.

**Comment by PaulMaas** [comment]
@keithwhor ilike is not the same as iequals. For example: 'a' iequals 'AA' = false whereas 'a' ilike 'AA' = true. Also, you asked me to create a ticket and PR for this a couple of weeks ago, lol.

I noticed in the DB true and false showing up as t and f, but I thought it was just psql showing a short-hand. My bad!
