### ISSUE TITLE
Any suggestions for deploying nodal app to cloud like openshift, heroku

### ISSUE THREAD

**Issue by arshadalisoomro** [keithwhor/nodal#185]
I love __nodal__, it is awesome and very easy to develop smart data driven apps, but I have a question How can we deploy nodal app to cloud like openshift, heroku any official resource or friendly suggestion Please.
Waiting to hear from you soon.

**Comment by pewh** [comment]
Hi @arshadalisoomro,

You can deploy nodal app to heroku by reading [this guide](https://github.com/keithwhor/nodal/wiki/Deploying-on-Heroku)

And I'm agree with you, nodal is **awesome!**
Hope it help you :)

**Comment by bmann** [comment]
@arshadalisoomro does that answer your question? The Heroku way is pretty easy, it "just works". I haven't used OpenShift, please do add your notes if you deploy to it.

**Comment by arshadalisoomro** [comment]
@bmann Sorry, but the Heroku is not the choice for me and unfortunately I'm not familiar to it as I'm fan of openshift and trying to deploy NodalJs app as node js app then I'll see what happens next.

**Comment by bmann** [comment]
@arshadalisoomro here's a link to NodeJS instructions for OpenShift -- https://developers.openshift.com/en/node-js-overview.html -- please let us know if you get somewhere with this.

**Comment by intabulas** [comment]
if you add --heroku as a param to `nodal new` it will generate an update readme and an app.json for one click heroku deploy

**Comment by keithwhor** [comment]
Thanks for the help guys - gonna close for now. :)
