### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by benjamingr** [keithwhor/nodal#19]
Given they're in the language standard now, it would probably be the better idea to use them or at least support them - especially since people want to use async/await or generator coroutines in new code.

**Comment by keithwhor** [comment]
Definitely considering what working with Promises would look like in Nodal, and appreciate the feedback. :)

**Comment by benjamingr** [comment]
Well mostly,
 
 - controller methods can return promises (which are resolved and returned as json or rejected as errors).
 - API methods (orm for instance) return promises instead of taking callbacks.

**Comment by davej** [comment]
:+1:, particularly on the promise interface for the ORM. You can still expose the `end` method for backwards compatibility if desired.

**Comment by benjamingr** [comment]
Or do like mongoose and return a promise if and only if no callback is passed

**Comment by chrisenytc** [comment]
:+1:

**Comment by erf** [comment]
+1 couldn't the controller routes be generator functions like in KOA ?

**Comment by keithwhor** [comment]
Closing right now; no intention to use promises in short-term future. Will re-approach in time.

**Comment by arcseldon** [comment]
+1 for promises support.

**Comment by christophehurpeau** [comment]
+1 for promises support.

**Comment by tilap** [comment]
+1 for promises support.

**Comment by ncksllvn** [comment]
I used [Bluebird's promisifyAll](http://bluebirdjs.com/docs/api/promise.promisifyall.html) as a quick way to add promise support.

**models/overrides.js**
``` javascript
  var Promise = require('bluebird')
  var Nodal = require('nodal')
  var Composer = require('nodal/core/required/composer')

  Promise.promisifyAll(Nodal.Model)
  Promise.promisifyAll(Nodal.Model.prototype)
  Promise.promisifyAll(Composer.prototype)
```

**controllers/dogs_controller.js**
``` javascript

show(){
    Dog.
        findAsync( this.params.route.id ).
        then(dog => this.respond(dog)).
        catch(err => this.respond(err))
}
```

Hope this helps!!

**Comment by sylvainlap** [comment]
+1 for promises support.
