### ISSUE TITLE
How to create a scheduled task?

### ISSUE THREAD

**Issue by troyconquer** [keithwhor/nodal#191]
Hi there,

First off, thank you this tidy library. I've been playing around with it on and off. And I'm excited to understand it better.

I'm struggling a little bit too long to create a task, scheduled to run every 5 minutes. I've dug some digging in the docs and repo/issues and can't find anything. I saw last month @intabulas was doing some refactoring on tasks.

I've tried `nodal g:task checker`. Then modified `schedulers/main.js` :
```
...
  const DummyTask = Nodal.require('tasks/dummy_task.js');
  const Checker = Nodal.require('tasks/checker.js');

  /* generator: end imports */

  /* generator: begin tasks */

  // scheduler.minutely(30).perform(DummyTask);
  console.log('*******');
  scheduler.minutely(1).perform(Checker);
...
```

Thank you for writing this and sharing it. I really appreciate it and do admire the code hygiene. And thank you in advance for any help.

Troy

**Comment by SteffenJahr** [comment]
Hi troyconquer,

what exactly is your problem? That it is not documented how to start the scheduler? Or do you want that the documentation is extended about how to create tasks?

As I see in your code you successufully created a new task that runs every minute. I think that's what you want? 

To start the scheduler you have to start it with node:

`node worker.js`

Steffen

**Comment by troyconquer** [comment]
Actually `node worker` or `npm run worker` work great. `npm start worker` just started the http server workers.

I was a little confused, I thought `nodal s` would start all the processes, http or scheduled worker.

Thanks for the quick response!

Troy
