### ISSUE TITLE
CORSMiddleware not working with Authorization header

### ISSUE THREAD

**Issue by SteffenJahr** [keithwhor/nodal#193]
In my project I use the delivered `CORSMiddleware` as well as the predefined access_token model.

To authorize my application requests I don't send the access_token as parameter. I send it as `Authorization` header. To access the API from another url I activated the `CORSMiddleware`.

But if I make an API call and send my `Authorization` header with my access_token I get an CORS error. This is because the Controller (Nodal.Controller) sets the `Access-Control-Allow-Headers` in the `allowOrigin()`method that is called from the CORSMiddleware.

`this.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');`

At this point the `Authorization` header is not included and so the authorization with the header is not working.

**Comment by SteffenJahr** [comment]
As workaround I modified the cors_middleware.js and added following code:

`controller.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');`

**Comment by keithwhor** [comment]
I'll add this line to the CORSMiddleware default :)

**Comment by keithwhor** [comment]
Actually, if you can add it I can merge the PR
