### ISSUE TITLE
Delete access_token using Authorization header

### ISSUE THREAD

**Issue by SteffenJahr** [keithwhor/nodal#194]
In my project I use the `Authorization`header to send the access_token to the API and authorize my API calls. I use the predefined access_token model/controller you ship with the project.

If you use the Authorization-header and want to destroy the access_token you don’t send any id to the server. You only call http://localhost:3000/api/access_token with method DELETE and send the Authorization-header. The problem is, that in the core code of Nodal there is this code:

`convertMethod(method, id) {

      let acceptMethods = {
        'GET': ['index', 'show'],
        'PUT': ['put', 'update'],
        'POST': ['create', 'post'],
        'DELETE': ['del', 'destroy'],
        'OPTIONS': ['options', 'options']
      };

      let hasId = !!(id | 0);

      method = method in acceptMethods ? method : 'GET';
      method = acceptMethods[method][hasId | 0];

      return method;

    }`

and this code always uses the ‘del’ method für the DELETE because there is no parameter sent.

**Comment by keithwhor** [comment]
The solution is to change to using the `del()` method for auth token removal instead of `destroy()` on the Controller.
