### ISSUE TITLE
501 - Not Implemented in PUT verb

### ISSUE THREAD

**Issue by cezarpretto** [keithwhor/nodal#197]
Hello friends. My API is returning this error when I try to update a register by PUT verb. Am I doing something wrong?? Is PUT the correct ver to use to update??

Thanks since sow!

**Comment by cezarpretto** [comment]
If I try in postman it works. But if i try on the code or in RestConsole it not work.

**Comment by keithwhor** [comment]
What do you mean try in code?

What HTTP verb does RestConsole send?

**Comment by cezarpretto** [comment]
What I want to say is when I try make a http request from javascript.

The verb is also PUT in rest console.

The request headers in rest console are:

Content-Type: application/json
Accept: */*
Connection: keep-alive
Origin: chrome-extension: //rest-console-id
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by keithwhor** [comment]
I'll check it out and get back to you in a bit :)

**Comment by cezarpretto** [comment]
Thanks =)

**Comment by keithwhor** [comment]
I can't reproduce this error - can you show me the code you're sending to the webserver? When I send an XHR with 'PUT' as the HTTP method, `put()` works fine.

**Comment by cezarpretto** [comment]
I'm using Angular and that's the code that I have in a service:

this.update = function(subscribe){
  return $http.put('http://localhost:3000/v1/users', subscribe);
};

GET, POST and DELET work fine only PUT returns the error.

**Comment by keithwhor** [comment]
What's the actual *request* angular is sending with that method call?

**Comment by cezarpretto** [comment]
That's what I receive from API:

http://pastebin.com/WnRxkLjZ

Here you can see the config headers and the response headers too.

**Comment by cezarpretto** [comment]
if you want you can clone my API repo. It's a simple API. It has just one controller rsrsrs

https://github.com/cezarpretto/dm-api

**Comment by keithwhor** [comment]
It's not a problem with Nodal, it's a problem with Angular's `$http` library. I need to see the request it's sending, copy and pasted from your Chrome console. It's likely doing something like `_method=PUT` but actually sending a POST request.

**Comment by cezarpretto** [comment]
I printed when the request is intercepted by cors in node. The problem is that angular and jquery http transform the request type PUT to OPTIONS. It happens only with PUT verb.

Here is whats is arriving in cors middleware:

V1UsersController {
  _path: '/v1/users',
  _method: 'OPTIONS',
  _requestHeaders: 
   { host: 'localhost:3000',
     connection: 'keep-alive',
     'access-control-request-method': 'PUT',
     origin: 'http://localhost:9000',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36',
     'access-control-request-headers': 'accept, content-type, x-http-method-override',
     accept: '*/*',
     referer: 'http://localhost:9000/',
     'accept-encoding': 'gzip, deflate, sdch',
     'accept-language': 'pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4' },
  _headers: 
   { 'Access-Control-Allow-Origin': '*',
     'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept',
     'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS' },
  _status: 200,
  _responder: [Function],
  _securityPolicies: {},
  params: 
   { buffer: <Buffer >,
     query: StrongParam {},
     body: StrongParam {},
     path: '/v1/users',
     auth: {},
     matches: [ undefined ],
     route: { id: '' },
     remoteAddress: '::1',
     id: '' },
  middleware: ExecutionQueue { _queue: [ CORSMiddleware {} ] },
  renderware: ExecutionQueue { _queue: [ GzipRenderware {} ] } }

**Comment by keithwhor** [comment]
When the `$http.put()` method executes in Chrome, a XHR network request is created. I need to see that data first.

Options should always return HTTP 200 OK.

**Comment by cezarpretto** [comment]
That's the content of angular request:
[](http://pastebin.com/SLwm5xRs)

Is it what you want?

**Comment by keithwhor** [comment]
No. Can you look in your Chrome network console and see what the actual request that's being sent is?

**Comment by keithwhor** [comment]
Alternatively you can use this module instead of `$http`:

https://raw.githubusercontent.com/keithwhor/nodal-angular/master/src/angular/app/factories/api.js

Just set `window.globals.api_url` to your localhost before you load it, and then use
```
API.request('path/to/endpoint').index(queryObject, callback);
API.request('path/to/endpoint').create(postObject, callback);
API.request('path/to/endpoint').show(id, queryObject, callback);
API.request('path/to/endpoint').update(id, posObject, callback);
API.request('path/to/endpoint').destroy(id, queryObject, callback);
```

**Comment by cezarpretto** [comment]
@keithwhor man you saved me hahha. Thanks a lot! It works fine :)

I'm going close the issue. Really thanks for your time!!
