### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by rish** [keithwhor/nodal#199]
With the [0.8 release announcement](http://www.nodaljs.com/devlogs/nodal-goes-api-first-with-0-8-release), it would be good to tag releases.

Especially with the [new updated roadmap](https://github.com/keithwhor/nodal/blob/5e850791fda52f3fb96e0650e6f7ee6dec7363ed/ROADMAP.md), issues can be assigned to [milestones](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) etc.

**Comment by SteffenJahr** [comment]
And release notes would be finde :)

**Comment by keithwhor** [comment]
Yep. I'll get on it.

**Comment by rish** [comment]
@keithwhor Cheers!

**Comment by keithwhor** [comment]
v0.11.0 and up will be tagged :) already implemented.
