### ISSUE TITLE
Why IIFES around everything?

### ISSUE THREAD

**Issue by timoxley** [keithwhor/nodal#20]
Why are all of the modules in the examples wrapped in an IIFE?

**Comment by FWeinb** [comment]
I was going to ask exactly the same. 

This 
```js
module.exports = (function() {
  'use strict';

  const Nodal = require('nodal');
  class TweetController extends Nodal.Controller {
    index() {
      Tweet.query()
        .where(this.params.query)
        .end((err, models) => {
          this.respond(err || models);
        });
    }
  }

  return Tweet;
})();
```

Could be written like:
```js 
'use strict';
const Nodal = require('nodal');

module.exports = class TweetController extends Nodal.Controller {
  index() {
    Tweet.query()
      .where(this.params.query)
      .end((err, models) => {
      this.respond(err || models);
    });
  }
}
```

**Comment by ojosdegris** [comment]
Or even better use ES6 export:

     'use strict';
     const Nodal = require('nodal');

     export class TweetController extends Nodal.Controller {
         index() {
             Tweet.query()
                 .where(this.params.query)
                 .end((err, models) => {
                     this.respond(err || models);
                 });
            }
     }

**Comment by FWeinb** [comment]
That would give a different export signature. You would export object with a key `TweetController`. Better would be to use `export default` in this case if you want to go full es6.

**Comment by chesstrian** [comment]
You'd have to change `Nodal.require` method to use `import` instead of `require`.

**Comment by FWeinb** [comment]
Changing `Nodal.require` to `import` won't work because ES6 modules need to be able to statically resolve their dependencies. So you can't have dynamic `imports`.

**Comment by chesstrian** [comment]
Oh, you're right, it means then export default cannot be used unless you use `import` instead of `Nodal.require`.

**Comment by FWeinb** [comment]
That is not correct doing this: 
```
 'use strict';
 const Nodal = require('nodal');

 export default class TweetController extends Nodal.Controller {
     index() {
         Tweet.query()
             .where(this.params.query)
             .end((err, models) => {
                 this.respond(err || models);
             });
        }
 }
```
is compatible with the IIFE currently used. (Note the `default` there)

**Comment by benjamingr** [comment]
Although what you'd really want is:

```js
import Nodal from "nodal";

export default class TweetController extends Nodal.Controller {
  index() {
    return Tweet.query().where(this.params.query).end(); // with the proposed promises support
  }
}
```

**Comment by jmcneese** [comment]
:+1: for @benjamingr

**Comment by keithwhor** [comment]
To quote my response on HN,

```
I like the IIFE because of the way it reads. A developer new to Node.js It's impossible to miss. Putting your export line at the bottom is begging for silly bugs. Even if they're quick fixes, still annoying.
```

Going to keep this pattern for now, until I change the entire module system to ES6.
