### ISSUE TITLE
Cannot Start Server

### ISSUE THREAD

**Issue by thomasqbrady** [keithwhor/nodal#206]
I have Node 5.3.0.

I have installed Nodal.

If I run `nodal new`, then `nodal s`, I get this error message:

> my-nodal-project@0.0.0 start /Users/tbrady/Development/nodalTest/my-nodal-project
> node server.js --harmony_classes

> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> [Nodal.Daemon] Startup: Initializing
> [Nodal.Daemon] Startup: Spawning HTTP Workers
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
> [Nodal.Daemon] Startup: Initializing
> [Nodal.Daemon] Startup: Initializing
> [Nodal.Daemon] Shutdown: Exited with code 1
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> [Nodal.Daemon] Shutdown: Exited with code 1
> [Nodal.Daemon] Startup: Initializing
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> [Nodal.Daemon] Startup: Initializing
> [Nodal.Daemon] Shutdown: Exited with code 1
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> [Nodal.Daemon] Shutdown: Exited with code 1
> [Nodal.Daemon] Startup: Initializing
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> [Nodal.Daemon] Startup: Initializing
> [Nodal.Daemon] Startup: Initializing
> [Nodal.Daemon] Shutdown: Exited with code 1
> [Nodal.Daemon] Shutdown: Exited with code 1
> [Nodal.Daemon] Shutdown: Exited with code 1
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> [Nodal.Daemon] Startup: Initializing
> [Nodal.Daemon] Shutdown: Exited with code 1
> /Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65
>         let child = cluster.fork();
>                             ^
> 
> TypeError: cluster.fork is not a function
>     at Daemon.start (/Users/tbrady/Development/nodalTest/my-nodal-project/node_modules/nodal/core/required/daemon.js:65:29)
>     at /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:9:10
>     at Object.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:15:3)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
>     at startup (node.js:141:18)
>     at node.js:980:3
> [Nodal.Daemon] Idle: Unable to spawn HTTP Workers, listening on port function (app) {
> 
>     app.listen(Nodal.my.Config.secrets.port);
> 
>   }
> [Nodal.Daemon] Shutdown: Exited with code 1
> /Users/tbrady/Development/nodalTest/my-nodal-project/server.js:11
>     app.listen(Nodal.my.Config.secrets.port);
>        ^
> 
> TypeError: Cannot read property 'listen' of undefined
>     at Server.<anonymous> (/Users/tbrady/Development/nodalTest/my-nodal-project/server.js:11:8)
>     at Server.g (events.js:260:16)
>     at emitNone (events.js:67:13)
>     at Server.emit (events.js:166:7)
>     at emitListeningNT (net.js:1263:10)
>     at nextTickCallbackWith1Arg (node.js:444:9)
>     at process._tickCallback (node.js:366:17)
> 
> npm ERR! Darwin 15.3.0
> npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v5.3.0
> npm ERR! npm  v3.3.12
> npm ERR! code ELIFECYCLE
> npm ERR! my-nodal-project@0.0.0 start: `node server.js --harmony_classes`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the my-nodal-project@0.0.0 start script 'node server.js --harmony_classes'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the my-nodal-project package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server.js --harmony_classes
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls my-nodal-project
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/tbrady/Development/nodalTest/my-nodal-project/npm-debug.log

**Comment by keithwhor** [comment]
Yeah, it's a dotenv issue. Will push a fix in a moment.

**Comment by keithwhor** [comment]
Should be fixed with https://github.com/keithwhor/nodal/commit/bf2075d9ecaa7300ffcb54e86f86d3f9c0f0b616

Upgrade to 0.8.3 :)

**Comment by keithwhor** [comment]
Actually, that's weird, try upgrading to Node 5.7.0. No idea why you're getting cluster errors.

**Comment by thomasqbrady** [comment]
Hmm. I upgraded to 5.9.0 (just lazily called upgrade on Homebrew), and no change.

Is there documentation on setting the needed env variables? I didn't see any.

**Comment by thomasqbrady** [comment]
Couldn't be [the left_pad thing](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/), could it?

**Comment by keithwhor** [comment]
It shouldn't be the dotenv stuff, but upgrade to Nodal 0.8.3 and try again.

**Comment by thomasqbrady** [comment]
> ➜  pharma-rep git:(master) ✗ nodal version
> Nodal Version: 0.8.3
> ➜  pharma-rep git:(master) ✗ node --version
> v5.9.0

No change. Should I try to downgrade Node to 5.7.0?

**Comment by keithwhor** [comment]
```
npm uninstall nodal -g
npm cache clear
npm install nodal -g
```

**Comment by thomasqbrady** [comment]
Never mind. It's now working on new projects. I was testing in the wrong directory (a project created with the older version of Nodal).

**Comment by keithwhor** [comment]
Cool! Thanks for letting me know :)
