### ISSUE TITLE
How to order by calculated/computed field ?

### ISSUE THREAD

**Issue by canuzunoglu** [keithwhor/nodal#207]
I would like to use wilson's score algorithm in my API but i don't have any idea or where do I start from?

**Comment by keithwhor** [comment]
You'll have to order *after* the query has finished. When you have the completed `models` object from the query, (i.e. `.end((err, models) => { ... })`), use:

```
models = models.sort((a, b) => a.get('calculated_field) - b.get('calculated_field'));
```

We don't currently support calculated fields at the database level, allowing you to sort during the query.
