### ISSUE TITLE
How to perform async validation on Nodal.model?

### ISSUE THREAD

**Issue by tilap** [keithwhor/nodal#208]
```__validate__``` method for ```Nodel.model``` perform a [loop on sync function](https://github.com/keithwhor/nodal/blob/master/core/required/model.js#L486)

However, I want to check if a model object property is not already used (example: a user email) and get some info from a remote service. So I need to query the database/fetch data from other service in async way. How can I do that?

**Comment by keithwhor** [comment]
You can't currently. I'll put it on the roadmap. :)

**Comment by keithwhor** [comment]
This is in! As of 0.10 :)

http://www.nodaljs.com/devlogs/nodal-0-10-landed--async-validations--file-uploads
