### ISSUE TITLE
findOrCreate

### ISSUE THREAD

**Issue by michelleheh** [keithwhor/nodal#233]
I mentioned on Keith's gitter page that we would like a findOrCreate method on the model.  We added the following to model.js, and it helped with implementing 3rd degree normalization in the postgres database.  Please let us know whether this is something you would like to add to the next version, I would love to make a pull request and contribute!

    /**
    * Finds the first record matching data, and return the model found. If no record found, create a new record and return the model.
    * @param {object} data The data to load into the object.
    * @param {function({Error} err, {Nodal.Model} model)} callback The callback to execute upon completion
    */
    static findOrCreate(data, callback) {

      new Composer(this)
        .where(data)
        .end((err, models) => {
          if (err) return callback(err);
          if (models[0]) {
            callback(err, models[0]);
          } else {
            let model = new this(data);
            model.save(callback);
          }
        });
    }

**Comment by keithwhor** [comment]
This will be supported in the 0.10.x release, which should land tomorrow :).

**Comment by keithwhor** [comment]
Done in 0.10 :)
