### ISSUE TITLE
Schema Field Unique Property Working as Intended?

### ISSUE THREAD

**Issue by nsipplswezey** [keithwhor/nodal#234]
An empty or non-unique value sent in a POST request to an endpoint that implements a field that implements the unique property will return an error as expected, but increments the `id` value of the user table.

Nit pick, and I suspect it's possible this just might be how Postgres doest, but it seems potentially unnecessary.

To reproduce sending a POST request to the user endpoint with a non-unique email.

Specifically

```
$ nodal new recreate-issue-api
$ cd recreate-issue-api
$ nodal g:model --user
$ nodal db:create
$ nodal db:prepare
$ nodal db:migrate
$ nodal g:controller --for user
$ nodal s
```

Then POST to the /user/ endpoint _twice_ with

```
username : test
email : test@test.com
password : password
```

Then POST again with a unique email
```
username : test
email : testtest@test.com
password : password
```

GET to /user/
Screenshot sequence:

![screen shot 2016-05-08 at 8 14 58 am](https://cloud.githubusercontent.com/assets/7946707/15098566/10be1796-14f5-11e6-80ac-6ce88063e776.png)
![screen shot 2016-05-08 at 8 15 01 am](https://cloud.githubusercontent.com/assets/7946707/15098567/13396aa2-14f5-11e6-87ac-b4e575206d17.png)
![screen shot 2016-05-08 at 8 15 07 am](https://cloud.githubusercontent.com/assets/7946707/15098569/1546ae54-14f5-11e6-8025-f1ba07fa3a17.png)
![screen shot 2016-05-08 at 8 15 15 am](https://cloud.githubusercontent.com/assets/7946707/15098572/17a2987a-14f5-11e6-9eb4-977c1effd7b7.png)

**Comment by keithwhor** [comment]
Not an error, just the way PG handles sequences.
