### ISSUE TITLE
How to add/remove fields to/from an existing model?

### ISSUE THREAD

**Issue by lukasbuenger** [keithwhor/nodal#238]
Imho one of the key requirements of a migration solution is the ability to mutate existing model schemata. While I'm perfectly aware of the fact that this is very much non-trivial I still would like to know if there are any plans on that.

**Comment by keithwhor** [comment]
No sweat! We actually already support this.

https://github.com/keithwhor/nodal/wiki/Adding-new-fields---columns-to-an-existing-model

:) Just not well-documented as of right now. Thanks for pointing this out.
