### ISSUE TITLE
Common Postgres Error

### ISSUE THREAD

**Issue by nsipplswezey** [keithwhor/nodal#239]
During their first Nodal app, users often run into issues with Postgres.

Since Nodal offers out of the box integration with Postgres, addressing these setup issues will help make starting a new Nodal project as frictionless as possible.

Issues:
If a user is running windows, what's a good Postgres.app alternative?
If a user doesn't want to get Postgres.app, what should they do?

`nodal db:create`

will sometimes throw something like 

`no actor postgres detected`

Essentially this means that there isn't a postgres username called `postgres` set up in their postgres instance.

I also often see

`no postgres server found at localhost:5432`

as well.

Let's add some useful error response so that if a user does a 

`nodal db:create`

and they don't have postgres installed, we point them to the best place on mac, and the right place on windows.

And if their postgres instance isn't set up correctly, we point them towards how to get it going.

**Comment by keithwhor** [comment]
Gonna take care of this with https://github.com/keithwhor/nodal/issues/252.
