### ISSUE TITLE
Middleware is only 'exec' when calling render()

### ISSUE THREAD

**Issue by seivan** [keithwhor/nodal#24]
I was planning on adding Strong Param support and couldn't decide between implementing it in the router or controller superclass so I thought I could just make a middleware out of it. 
The benefit is that it could be disabled to keep backward compatibility for older apps. 

However from the looks of it, the middleware are only executed when render() is called.

My take is, if it's moved to router delegation, one could implement more of nodal features as middleware (that can be disabled) instead of hardcoding them into the system. Honeypot, ip-redirect, etc.

**Comment by keithwhor** [comment]
I'm going to close this and we can continue discussion in https://github.com/keithwhor/nodal/issues/25, that ok?

:)
