### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by BinaryNate** [keithwhor/nodal#26]
I just wanted to make sure you're aware - Nordic Semiconductor uses the same logo.

![Nordic logo](http://www.nordicsemi.com/extension/nordic/design/bootnordic/images/NordicS_smarter-things.png)

**Comment by keithwhor** [comment]
Yes, they're quite similar. I'm fond of the logo, I'll have a discussion with the designer to see if we can figure out something that's clean and not so similar :).

**Comment by BinaryNate** [comment]
For what it's worth, I think your version without the gradient looks nicer. I just wanted to bring this to your attention, so I'll close this issue out now.
