### ISSUE TITLE
disable clustering / vscode

### ISSUE THREAD

**Issue by sylvainlap** [keithwhor/nodal#262]
Is there any way to disable clustering at launch, because as-is, the VS Code debugger cannot work with Nodal.

**Comment by keithwhor** [comment]
I have no intention of doing this at present --- apologies, I recommend debugging code with console logging as of now. It's  a useful practice to get the hang of. :)

**Comment by TimofeyBiryukov** [comment]
I tried debugging with WebStorm debugger, it also would not work with a cluster it seams.
So it looks like debugging Nodal is not happening for sometime.
