### ISSUE TITLE
only support PostgreSQL, couldn't support MySQL？

### ISSUE THREAD

**Issue by arden** [keithwhor/nodal#268]
only support PostgreSQL, couldn't support MySQL？

**Comment by jeansaigne** [comment]
I vote to do not develop this feature for now, stick to postgres.
Nodal support  Postgres and it's THE pragmatic solution to work with when developing with entreprise scalability constraints.
I'm telling you buddy Keithwhor, i am actually putting up and entire application for my entreprise and my api is based on your Framework, thank you for that, good job.

**Comment by keithwhor** [comment]
@jeansaigne thank you! mind sending me an email (keith [at] polybit [dot] com) to talk about your use case? would love feedback

Plan is stick to PG right now. I've been debating moving to MySQL but it's not in the cards as of now, and it's looking less likely as time goes by.
