### ISSUE TITLE
Passport authentication

### ISSUE THREAD

**Issue by jeansaigne** [keithwhor/nodal#271]
Hi,
Could you add passport authentication support ?

(Or maybe i should handle it via a merge request ?)

Thanks for consideration.

**Comment by keithwhor** [comment]
Not quite sure what you're referring to - can you give an example?

**Comment by sylvainlap** [comment]
PassportJS is a middleware for ExpressJS. Not sure it will fit for Nodal.

**Comment by keithwhor** [comment]
No, it won't. We can work on a package to do the equivalent for you, though. It's an important feature.

**Comment by jeansaigne** [comment]
Since, i understood the essence of my stupidity. I'm actually working on this passport-like feature.

Keep going keithwhor you're doing a great job, and thank you both for the replies despite my absence.

**Comment by shams-ali** [comment]
any update on this?, i need to add facebook login to an already built out nodal app using its built in auth, ideas on if it would it be to try and integrate the two or just integrate passport local and facebook?
