### ISSUE TITLE
Nodal db:seed fails silently if property name in seed.json does not exactly match model name

### ISSUE THREAD

**Issue by nsipplswezey** [keithwhor/nodal#272]
For example

nodal new seed-test
nodal g:model Place 
nodal g:model Place slug:string name:string zipcode:int latitude:float longitude:float
nodal db:create
nodal db:prepare
nodal db:migrate
nodal db:seed //fails silently because Places does not match Place

Should do a fuzzy string comparison between model names and properties of the seed JSON file, and prompt the user to match names exactly.

Simple improvement would just be to log a response to a `nodal db:seed` that results in no seeding of data "Looks like you didn't seed any data. Do your model names in /app/models exactly match your model names in seed.json?"

```
"development": {
    "Places": [
      {
        "slug" : "crema-coffee-and-bakery",
        "name" : "Crema Coffee and Bakery",
        "zipcode" : "97214",
        "latitude" : "",
        "longitude" : ""
      },
      {
        "slug" : "venice-grind",
        "name" : "Venice Grind",
        "zipcode" : "90066",
        "latitude" : "",
        "longitude" : ""
      },
      {
        "slug" : "eoki",
        "name" : "EOKI",
        "zipcode" : "",
        "latitude" : "",
        "longitude" : ""
      }
    ]
  },
```

**Comment by keithwhor** [comment]
I'm ok with this for now. If somebody submits a PR I'll get to it but not a top priority.
