### ISSUE TITLE
GraphQL support & doc

### ISSUE THREAD

**Issue by sylvainlap** [keithwhor/nodal#279]
I can't find any reference to GraphQL in docs, README or LEARN.md.
Does Nodal handle GraphQL ? Where can I find some documentation about it ?

**Comment by jeansaigne** [comment]
Hi Sylrvainlap,
I found [this link](http://graphql.nodaljs.com) showing several examples using GraphQL with Nodal, i hope it will help...

**Comment by keithwhor** [comment]
What @jeansaigne mentioned is all we have right now. We'll have a lot more documentation coming soon, I promise! In a bit of a sprint right now building out a product. :)
