### ISSUE TITLE
joinedBy

### ISSUE THREAD

**Issue by sylvainlap** [keithwhor/nodal#284]
It seems that joinedBy is deprecated, but its still referenced
- in docs: https://github.com/keithwhor/nodal/blob/39351a777d5a67048efa2d2de5112a684505896b/docs/index.html
- in model.js: https://github.com/keithwhor/nodal/blob/49c9d62b51a8962b3c0c33691931f6916a0b3796/core/required/model.js

**Comment by keithwhor** [comment]
I haven't updated the docs yet. Good catch. :) Thank you!
