### ISSUE TITLE
Don't expose a new syntax and instead subscribe to API standards

### ISSUE THREAD

**Issue by hpoom** [keithwhor/nodal#285]
I feel that although the query parameters mapped to the ORM is powerful, instead of copying Django with things like `id__gte=3` instead the default out the box for Nodal should be to subscribe to either [json:api](http://jsonapi.org/) or [HAL](http://stateless.co/hal_specification.html) as an API standard.

json:api for example would support filtering and pagination in a standard way.

Ideally the API user should be abstracted away from the data store behind the scenes. Most implementations over time will involve doing more than mapping REST to CRUD and will require those using the framework to add increasing business logic between the CRUD operations on the data store and API payload being sent back to the API consumer, making the current method of query parameters not suitable.

**Comment by keithwhor** [comment]
Thanks for the feedback, but I disagree. I want to give front-end developers increasing control over and insight into the way endpoints are implemented. If anything, we're going to be heading *moreso* in that direction and away from traditional implementations like json:api or HAL.
