### ISSUE TITLE
How to set column default from migration file?

### ISSUE THREAD

**Issue by MrSkinny** [keithwhor/nodal#287]
Say I want a db column to have a default value?  I tried:

```
this.createTable("products", [
  { "name": "rating", "type": "integer", "properties": { "default": 1 } }
]);
```

But the `schema.json` file created has an empty `properties` object.

**Comment by jeansaigne** [comment]
Hi again MrSkinny,
not really sure about this one but you should use "defaultValue" instead of "default".
Hope it'll help

**Comment by nikravi** [comment]
Neither 'default' or 'defaultValue' didn't work for me
