### ISSUE TITLE
Add TypeScript definition file.

### ISSUE THREAD

**Issue by charrondev** [keithwhor/nodal#297]
I already have a definition file I've made myself, mostly covering migration, models, and controllers, but I could finish it and make a pull request if you would be willing to include it in the project. It's just a 1-liner in package.json pointing to the definition. 

Not everyone uses typescript, but the extra information can really help autocomplete and discovery of the API even when just using javascript.

**Comment by miksansegundo** [comment]
+1

**Comment by nik-lus** [comment]
@Charrondev can you share that declaration file with me (somehow)...and maybe leave a quick how-to instructions to add to the nodal project ? 

Don't worry about finishing it, even some definitions would be better than none.

**Comment by Charrondev** [comment]
@nik-lus I submitted them to the official @types repo a while ago. You can submit a pull request there if you want to edit them. I've also linked them [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/2f711746366f18454e4ef689ce79b43ef76a3f3c/nodal).

Alternatively, if you use Typescript 2.0+ you could just use `npm install --save-dev @types/nodal`
