### ISSUE TITLE
Make "everything" into a Middleware for pipeline based code

### ISSUE THREAD

**Issue by seivan** [keithwhor/nodal#30]
So you can extract ParamParser, Cookies, Session, Loggers into their own modules and let people insert the middleware they want as replacement or above

Suggestions for middleware
 - Logging
 - Cookies
 - Response
 - Request
 - Routing 
 - Gzip

**Comment by keithwhor** [comment]
Yeah, I'll think through this. Thank you for the suggestion! Will talk through how it might look.

**Comment by seivan** [comment]
Would make things like CookieJar, HTTP Caching, Honeypot, IPBanning, Geo-tracking   easier. ;-)

**Comment by chrisenytc** [comment]
:+1:

**Comment by keithwhor** [comment]
@seivan Thought through this. Going to change current Middleware implementation to Renderware (and have it for like, Gzip, which needs to be done in post-processing) and add in a Middleware that intercepts HTTP requests. Should be ready EOD.

**Comment by keithwhor** [comment]
Done.
