### ISSUE TITLE
Using a Resource "DSL" for creating routes.

### ISSUE THREAD

**Issue by seivan** [keithwhor/nodal#32]
Would a Rails like syntax for creating routes fit in with the design of the framework? 
I'm using array splats to take more than one argument. Would have to check the order. 
Still learning ES6, so please let me know if I'm missing something here.

```javascript
const UserController = Nodal.require('app/controllers/user_controller.js');
const PhotoController = Nodal.require('app/controllers/photo_controller.js');

//All verbs
router.resources(UserController) // /user/<verbs>
router.resources(UserController, "/avatars") // /avatars/<verbs>

//Routes with just one data-set
//Trying to avoid passing magic boolean arguments, so using a different method name
router.singularResource(UserController) // /user/<verbs sans index no id>
router.singularResource(UserController, "/avatars") // /avatars/<verbs sans index, no id>

//Single routes
router.get(UserController)  // /users/:id - calls get()/show()
router.get(UserController, "/avatars")  // /avatars/:id - calls get()/show()
router.get(UserController, "/api/v1/avatars")  // /api/v1/avatars/:id - calls get()/show()

//Scoped routes
router.resources(UserController, {scope: "/api/v1"}); // /user/<verbs>
router.get(UserController, "avatars", {scope: "/api/v1"});  // /api/v1/avatars/:id - calls get()/show()

router.scope("/admin", scopedRoute => 
   scopedRoute.resources(UserController); // /admin/user/<verbs>
   scopedRoute.get(PhotoController, "/picture");  // /admin/pictures/:id - calls get()/show()
);

//Nested Routes
router.resources(UserController, nestedRoute => 
   nestedRoute.resources(PhotoController);
); // /user/<verbs>/photos/<verbs>



```

Btw, I genuinely love the source code. This is the cleanest javascript/MVC-framework source code I've ever seen. I've seen plenty. Seriously, well done!

**Comment by keithwhor** [comment]
Thank you very much. Those are very kind words. Mean a lot. :)

Not sure about what's proposed here. What advantages does this give us over the current routing system?

**Comment by seivan** [comment]
*Not* writing regex is the advantage :dancer: 
Reading routes should come natural. Parsing regex isn't as natural as seeing verbs. 

Actually, I think having the user write their routes with regex seems more error prone compared to having a structured pipeline in which you put your routes in.

**Comment by intabulas** [comment]
Been pondering this a few days.  I totally get regex can be a barrier to entry for folks not using `nodal g:controller`. I have also worked on some extremely large rails apps and the routes file was out of control  (or purely abused) and hard to grok as well.  If nodal isn't going to support controller#method routing (which right now I really appreciate it doesn't) or allow the rigid method mapping (GET -> Index/Show) to be changed then a DSL would do nothing more that remove some regex cruft

ie: `router.route(/^\/tweets\/?/, TweetsController);` to `router.route('/tweets', TweetsController);` 

There is a broader conversation imho about the router and named params (/tweets/:id/:somethingelse) for apps that aren't pure crud apps, that I would love to see take place

note: I surprisingly like the query params for join filters `/tweets/1?user__username=bob` but I do think most folks coming from rails (as an example) would expect /users/1/tweets to work also in that case

**Comment by keithwhor** [comment]
@intabulas Yeah... but maybe we get them out of that habit. I'd prefer one resource that you can query with whatever related object you'd like via the querystring. Makes it easier for frontend developers to build tools to interface with it.

I can add support for non-regex routes. I'm used to writing RE all of the time and I often forget how overwhelming it is the first time you see it. :)

**Comment by keithwhor** [comment]
Not sure if I want an entire DSL btw. For now I'll just add string matching.

**Comment by intabulas** [comment]
@keithwhor yeah I agree get folks out of the bad habit.. My last bit of hanging onto named path param is using a well known slug vs an id as the last param as a less transient/fragile resource reference

ie: `/car/tesla` vs `/car/13`... if your resource had `:id` or `:name` in the route you could do alternate searching.  I started mucking around with a find_by model method in a branch for another reason that could work.. Granted its implantation also would support `/car?name=tesla` :)

ref: https://github.com/intabulas/nodal/commit/01771c19b4f1b825979d54f79c72f236cd9cd08c

warning: its just a rough start

**Comment by seivan** [comment]
@intabulas So, ruby has this "weird" bug/feature where converting "123-tesla" would be just 123.
So your slug could be the id+slug parameterized title.

That way both ```/car/123-tesla``` and ```/car/123``` will work. In fact, if you changed your title, and the slug would change your book mark of ```/car/123-tesla``` will still work. It's actually kinda neat. I'd wish more Rails devs would use that. Seeing *only* ID in urls is boring, but they are necessary why not combined them.

**Comment by keithwhor** [comment]
Great discussion, closing this issue for now though. Will handle the id fetching with https://github.com/keithwhor/nodal/issues/114.

No plan for a DSL right now, but might approach in the future.
