### ISSUE TITLE
Fix COR Issues with nodal server

### ISSUE THREAD

**Issue by iitgrad** [keithwhor/nodal#321]
How can I accomplish adding these to all nodal responses?

Access-Control-Allow-Origin: editor.swagger.io
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept

**Comment by maxism** [comment]
@iitgrad you should use Nodal middleware. Run ``nodal g:middleware Swagger`` in you nodal project directory. Then replace exec method in ``src/middleware/swagger_middleware.js`` with
```js
exec(controller, callback) {

    controller.appendHeader('Access-Control-Allow-Origin', 'editor.swagger.io');
    controller.appendHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');

    callback(null);
    return false;

  }
```
And finally add to ``src/router.js`` following lines 
```js
const SwaggerMiddleware = Nodal.require('middleware/swagger_middleware.js');
router.middleware.use(SwaggerMiddleware);
```

**Comment by iitgrad** [comment]
Thank for this but it still doesn't work. I have also tried '*' to allow any website but it continues to fail.
