### ISSUE TITLE
Conditional join on one to one relationship

### ISSUE THREAD

**Issue by somecallmemike** [keithwhor/nodal#339]
I have two tables, properties and work_orders.  I need to create a relationship where I get work_orders (id, property_id, ...) and join to properties (id, company_id, ...) using the 'property_id' column in the work_orders table joined to the 'id' column of properties.  Then I need to do a conditional join where I restrict the result set of work_orders by the 'company_id' column in properties.  

I have the following relationship:
```
Property.joinsTo(WorkOrder, {via: 'id', multiple: false });
```
And the following query in work_orders_controller.js (Hopefully the conditional join syntax I am using is correct, please let me know if this looks incorrect):
```
    this.params.query['property__company_id__is'] = this.auth_params.user.company_id;

    WorkOrder.query()
      .where(this.params.query)
      .join('property', { company_id__is: this.auth_params.user.company_id })
      .end((err, models) => {
        this.respond(err || models, 
        [
          'id',
          'name',
          {'property':
            [
              'id',
              'name',
              'company_id'
            ]
          }
        ]);
      });
```
However the results set is joining the 'id' of property to the 'id' of work_order instead of the 'property_id' column.  Is there a way to specify which column in the parent table to join the child table to (properties.id => work_orders.property_id)?

**Comment by somecallmemike** [comment]
Anyone?

**Comment by jacoblee93** [comment]
Hi Mike,

Sorry about the delay. One thing I see that you shouldn't be doing is joining `via: id`. Try writing the relationship as:

```
WorkOrder.joinsTo(Property, {multiple: false}
```

This assumes that WorkOrder has a property named `property_id`. Let me know if that helps! Should also remove the need to do a conditional join, your query looks like it should be OK even without the `__is` at the end.

Best,

Jacob

**Comment by jacoblee93** [comment]
As an aside, you should use `via` for cases where you want to have different one to one relationships between two models. As an example, say you wanted WorkOrder to be associated with exactly two different Property models in semantically different ways. 

For example, you're doing the join from WorkOrder to a Property via the default `property_id`, but say a WorkOrder could have exactly one workshop associated with it that is also a Property in your database, you could have a `workshop_id` property on your WorkOrder and then have a line in your `relationships.js` file like this:

```
WorkOrder.joinsTo(Property, {via: workshop_id, multiple: false});
```

**Comment by somecallmemike** [comment]
Jacob,

When I remove the "via" I end up getting the following error: "column w1.work_order_id does not exist".  In this relationship the property_id column is in the work_orders table, and I need to join that property_id column back to the id column in properties, then restrict by properties.company_id.

Assuming the relationship syntax from the docs says child.joinsTo(parent), this is the relationship I added:
```
Property.joinsTo(WorkOrder, {multiple: false });
```
I am attempting to join the table "properties" to "work_orders" so that I can restrict the work_orders based on the company_id in the parent table of properties. Essentially making it so that someone in company XYZ cannot see rows from the work_orders table that are related to a property they do not own.

Thanks for the response!

**Comment by jacoblee93** [comment]
Ah I had it backwards then... My bad. Glad I could help!

**Comment by somecallmemike** [comment]
Jacob,

I actually didn't resolve the issue, I am still running into the error "column w1.work_order_id does not exist".  So the original question was how to I force the relationship to use the correct columns work_orders.property_id -> properties.id?

**Comment by jacoblee93** [comment]
Oh did 

```
WorkOrder.joinsTo(Property, {multiple: false});
```

not resolve your issue? That should do it, you can do joins in queries the other way too :)

**Comment by somecallmemike** [comment]
The system is erroring saying "message": "column w1.work_order_id does not exist".  What I believe is happening is the normal join expects the parent table to use an 'id' column, and the child table would have 'parent_table_id' column, hence it's looking for 'work_order_id' in properties because the join is making the work_orders table the parent.  I need to force the relationship to use 'work_orders.property_id' as the parent column, and join on the child column of 'properties.id'.

**Comment by jacoblee93** [comment]
If `WorkOrder.joinsTo(Property, {multiple: false});` isn't working for you (the other way around from what you tried), you could do something like this:

```
Property.joinsTo(WorkOrder, {via: id, using: property_id, multiple: false});
```

But that's pretty irregular. You shouldn't have to do that, and we should investigate why `WorkOrder.joinsTo(Property, {multiple: false});` isn't working for you -- could be a Nodal bug.

**Comment by somecallmemike** [comment]
Yes!  That worked!  It was the 'using' key that was missing, and now the records are returning only from the properties that are related to the correct company_id.  Thank you so much!

**Comment by jacoblee93** [comment]
Happy to help.
