### ISSUE TITLE
Development environment setup

### ISSUE THREAD

**Issue by michaelmior** [keithwhor/nodal#37]
It seems like the current recommendation for setting up a development environment is to manually install and configure a Postgres server. I'm going to suggest using [Docker Compose(https://docs.docker.com/compose/) as an alternative. I tried this myself with Nodal and it makes things a breeze. Basically the getting started would be reduced to `docker-compose up`. (Assuming Docker and Docker Compose are installed.)

Note that this doesn't necessarily preclude users from continuing to use their own setup, but given how popular Docker currently is, I suspect a lot of people would prefer the Docker route. Aside from documentation, only three changes are needed:

**Add a `Dockerfile` to build a container for the Nodal app**
```text
FROM node
EXPOSE 3000

RUN npm install -g --silent nodal

WORKDIR /usr/src/app
CMD ["npm", "start"]
``` 

**Add `docker-compose.yml` to define the service configuration**
```text
web:
  build: .
  ports:
   - "3000:3000"
  volumes:
   - .:/usr/src/app
  links:
   - db
  environment:
   - DATABASE_HOST=db
   - DATABASE_PORT=5432
   - DATABASE_USER=nodal
   - DATABASE_PASSWORD=nodal
   - DATABASE_DB=nodal_development
db:
  image: postgres
  environment:
   - POSTGRES_USER=nodal
   - POSTGRES_PASSWORD=nodal
   - POSTGRES_DB=nodal_development
```

**Modify the development database configuration to use environment variables**

This is the only slightly tricky bit. For the above to work, the production and development database configuration would have to be the same since the above relies on environment variables. However, I think this is actually an added bonus. If users don't want to use Docker, then using something like [dotenv](https://www.npmjs.com/package/dotenv) to read a set of environment variables configuring a local server would be an easy alternative.

I'm happy to put together a PR if this sounds like something you're interested in.

**Comment by keithwhor** [comment]
Docker support would be excellent. If you could throw together a PR and show me what it looks like, I would be very grateful. I have not yet played with Docker myself (!!) but am aware of how powerful it is, and this would be a great time to start.

**Comment by michaelmior** [comment]
Done. Let me know what you think :)

**Comment by keithwhor** [comment]
Still have to consider how we're going to handle environment variables. Will take a bit to get to this. Really appreciate your work, though!

**Comment by niallobrien** [comment]
Great stuff @michaelmior

**Comment by PaulMaas** [comment]
I am using docker and have it running successfully with Nodal 0.6. I have pretty much exactly the same Dockerfile and docker-compose.yml as @michaelmior :

Dockerfile:
```
FROM node

RUN npm install -g nodal

EXPOSE 3000

WORKDIR /usr/src/app
CMD ["npm", "start"]
```

docker-compose.yml:
```
app:
  build: .
  ports:
   - "8484:3000"
  volumes:
   - .:/usr/src/app
  links:
   - db
db:
  image: postgres
  volumes:
    - ao-admin-data:/var/lib/postgresql/data
```

Running the commands: ```nodal db:create``` and ```nodal db:prepare``` from the docker shell works great. Things go wrong when I try to create the user model ```nodal g:model --user```. The app daemon errors out and is unable to start again. If I undo the changes made by the ```nodal g:model --user``` command everything starts working again. The error seems to happen when ```node server.js --harmony``` runs.

Here is my npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ao-admin@0.0.0~prestart: ao-admin@0.0.0
6 silly lifecycle ao-admin@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle ao-admin@0.0.0~start: ao-admin@0.0.0
8 verbose lifecycle ao-admin@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ao-admin@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle ao-admin@0.0.0~start: CWD: /usr/src/app
11 silly lifecycle ao-admin@0.0.0~start: Args: [ '-c', 'node server.js --harmony' ]
12 silly lifecycle ao-admin@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle ao-admin@0.0.0~start: Failed to exec start script
14 verbose stack Error: ao-admin@0.0.0 start: `node server.js --harmony`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ao-admin@0.0.0
16 verbose cwd /usr/src/app
17 error Linux 4.1.13-boot2docker
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error ao-admin@0.0.0 start: `node server.js --harmony`
22 error Exit status 1
23 error Failed at the ao-admin@0.0.0 start script 'node server.js --harmony'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ao-admin package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js --harmony
23 error You can get their info via:
23 error     npm owner ls ao-admin
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

@michaelmior Have you performed the user model creation step successfully?

**Comment by PaulMaas** [comment]
I now don't think it has anything to do with docker. I'll create a new issue for this...

**Comment by michaelmior** [comment]
@PaulMaas Yeah, looks to me to be unrelated. Let me know if it is though and I can try to dig into what's going on.

**Comment by PaulMaas** [comment]
@michaelmior It is somewhat related after all. I created a new issue for it #150 . Discussion continues there...

**Comment by intabulas** [comment]
@keithwhor I wonder if we should add a prompt to `nodal new` for docker support and then have it tweek the db.json like we do now with database name to use env vars in dev config as well

**Comment by michaelmior** [comment]
That would be a reasonable compromise. Although I would still vote for
switching the config to always use env vars.

**Comment by intabulas** [comment]
@michaelmior thats effectively what would happen, db.json would get altered in the generated app to be all env var

**Comment by michaelmior** [comment]
@keithwhor Sure. I'm just suggesting that I don't see a strong need to have two separate cases. I would just switch to env vars all the time. But if you have a strong preference to only do that in the Docker case, that would definitely work :)

**Comment by bmann** [comment]
Documented in the wiki -- https://github.com/keithwhor/nodal/wiki/Running-Nodal-with-Docker-locally -- please add edits!

Can we close this?

**Comment by michaelmior** [comment]
@bmann It would still be nice to have an option for this to be set up automatically especially since it's pretty low overhead to do so. The problem with the instructions in the wiki is that they rely on Nodal picking up the set of environment variables given in `docker-compose.yml`. Nodal does not currently use those variables.

**Comment by bmann** [comment]
I'm just picking stuff up that is buried in issues and documenting it in the wiki to make it easy for other people to find. 
Agreed that a PR to provide core support would be good, needs someone who uses Docker to complete this.





On Sun, Feb 21, 2016 at 12:02 PM -0800, "Michael Mior" <notifications@github.com> wrote:












@bmann It would still be nice to have an option for this to be set up automatically especially since it's pretty low overhead to do so. The problem with the instructions in the wiki is that they rely on Nodal picking up the set of environment variables given in docker-compose.yml. Nodal does not currently use those variables.

**Comment by michaelmior** [comment]
@bmann I already put in a PR that adds Docker support but the team has decided not to go forward with this for now. At the very least, information on changing the config to use environment variables should be added to the wiki since it won't work as-is.

**Comment by bmann** [comment]
Great -- please edit the wiki. Thanks!



On Sun, Feb 21, 2016 at 1:59 PM -0800, "Michael Mior" <notifications@github.com> wrote:












@bmann I already put in a PR that adds Docker support but the team has decided not to go forward with this for now. At the very least, information on changing the config to use environment variables should be added to the wiki since it won't work as-is.

**Comment by keithwhor** [comment]
Archiving now.
