### ISSUE TITLE
Name for routes

### ISSUE THREAD

**Issue by manhhailua** [keithwhor/nodal#39]
Define routes with their name once and we can use them globally, such as: in views or client script.

**Comment by keithwhor** [comment]
Can you provide an example?

**Comment by CoolVoltage** [comment]
I guess @manhhailua is talking about this :

Let's say we name a route 'helpPage' :
`router.route(/^\/help\/?/, helpController, "helpPage" );`

And we can use the name in views as :
` <a href='{{= Routes.helpPage }}' >Help</a>`

**Comment by chrisenytc** [comment]
Sounds interesting the example  shown by @CoolVoltage :+1:

**Comment by manhhailua** [comment]
@CoolVoltage Thanks for your example.
I hope we can use routes name in client script somehow.
Example file: `/static/scripts/client.js`
`$.post(Routes.helpPage, callback);`

**Comment by danielgamble** [comment]
Yea Django do this quite nicely:

```python
    url(r'^nations/$', nation_list, name='nation-list'),
    url(r'^nations/(?P<pk>[0-9]+)/$', nation_detail, name='nation-detail'),
```

So you can just call the route name and never have to worry about updating the url in multiple places

**Comment by keithwhor** [comment]
Okay. Will mark this as enhancement and fit this in tomorrow

**Comment by keithwhor** [comment]
Archiving now. Will consider adding to roadmap in future but not a priority. Routes have changed completely, anyway.
