### ISSUE TITLE
Graphql support?

### ISSUE THREAD

**Issue by juliankrispel** [keithwhor/nodal#40]
How would that fit into the nodal ecosystem? I was going to try it out and prototype it, any thoughts/concerns @keithwhor?

**Comment by juliankrispel** [comment]
Also, thanks for open sourcing this, I've been keen on a framework like this :)

**Comment by ktmn** [comment]
This works for express, hapi, koa, wonder if it can be made to work with Nodal... https://github.com/RisingStack/graffiti

**Comment by keithwhor** [comment]
AFAIK I'm already doing some kind of similar things to GraphQL with model interfaces. Would be interested in exploring the similarities / differences more in depth and offering full GraphQL support, for sure. I'll look at resources on my own, do you have a few good links to the spec?

**Comment by kitze** [comment]
This library might maybe make the process easier? https://github.com/kadirahq/lokka

**Comment by kulakowka** [comment]
@keithwhor i have some links about GraphQL

https://learngraphql.com/ - Guide for beginners
https://github.com/chentsulin/awesome-graphql - awesome list for GraphQL

I would like to see support GraphQL out of the box. (or as a plugin for nodal)

**Comment by JesseScott** [comment]
Should this be closed with ** v0.7 **released ?

**Comment by keithwhor** [comment]
Yeah let's close it. We still don't have full support of the spec but we've started.
