### ISSUE TITLE
Negative interface matching?

### ISSUE THREAD

**Issue by Anachron** [keithwhor/nodal#41]
So instead of defining `[id, username, created_at]` as interface wouldn't it be better to do allow for the opposite and only define the things to hide? 

I propose thse following syntax: `['!password']` will hide the password and use all default fields.  This should also work in cascade relationships like `[{user: ['!password']}]`.

Now I don't need to worry to keep updating the interfaces everywhere when I created or remove a field from my model.

**Comment by keithwhor** [comment]
Hm, what if somebody does something like, `['username', '!password']`? I'm not opposed to the idea, but would like to consider some syntax alternatives.

**Comment by intabulas** [comment]
What about an option to specify default exclusions on the model itself, it would remove some of the interface copy pasta when doing joins. Obviously that still leaves syntax about when you do want to include it

**Comment by keithwhor** [comment]
So my initial implementation had developers defining "default interfaces" on the Model, which was default inclusions.

I removed it because it's combining view logic with model logic and it becomes a pain in the ass to trace down / is easy to forget about. For now, I'd prefer to focus on a syntax just for excluded fields using `arrInterface` in `Model#toObject()`. We can expand the use case from there if we need to, and perhaps tie something to the Model (so you don't repeat yourself everywhere), but that would be step 2.

**Comment by intabulas** [comment]
Yeah thats a really good point about model/view logic. Personally I don't mind the current implementation, I just don't like the copy pasta in controller methods.  Why not have, as you suggest,  `arrInterface` be a pure exclusion list. Seems a less confusing (and less typing) start. 

My only thought is would that be obvious to people. For example using the twitter/user stuff from the videos, would people understand this shows everything but password from both models

`this.respond(err || models, [{ user: ['password']}]);`

**Comment by keithwhor** [comment]
I do not like the idea of the interface being exclusionary instead of inclusionary. It should be inclusionary by default, it's easier to reason about. Perhaps `Model#toObject()` takes a second parameter, than when true, turns the interface to exclusionary.

**Comment by intabulas** [comment]
Works for me

**Comment by keithwhor** [comment]
Alright. I can do this --- a couple of other Model changes I want to make anyway. Will get to it this weekend.

**Comment by Anachron** [comment]
Yes I'm also fine with that one! :+1:

Sorry for my typos, I'm writing from mobile :)

**Comment by Anachron** [comment]
New idea: Why not responseWithout as new method (as opposite to response)? Could that be less confusing instead of a flag?

**Comment by keithwhor** [comment]
I'd rather just have a flag. "respondWithout" doesn't mean anything. Respond without what? Chances are a new dev would look up an API reference either way.

**Comment by Anachron** [comment]
Fair enough. Was just an idea.

**Comment by keithwhor** [comment]
Supported:
https://github.com/keithwhor/nodal/commit/0031b10329bcc48737ded85088207d41deab2dee

Must specify: `{exclude: true}` in options for `Model#toObject`.

Not linked up to `.respond` method yet.

**Comment by keithwhor** [comment]
Finished with https://github.com/keithwhor/nodal/commit/fd65291e516ec677cf2efd21235b0823f1404fca
