### ISSUE TITLE
Generate README.md and index controller from template on nodal new

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#45]
I am making this an issue vs just submitting a pr to see how folks feel about the idea.

When you run `nodal new` its prompts you for a name that is used in package.json.  However the default index_controller has a harcoded `My Nodal Application` in it. Including #43 in this though, it would be nice to have the name used at the time of `nodal new` in both the index controller and the readme.

I would like to propose we template-ize index_controller and a readme and use them to generate the necessary files

cc: #43 #36

**Comment by chesstrian** [comment]
:+1: to PR.

**Comment by keithwhor** [comment]
:+1: Sounds good.

**Comment by intabulas** [comment]
This was included in PR #46

**Comment by keithwhor** [comment]
Can I close? Or should we keep open until Deploy to Heroku button and app.json added?

**Comment by intabulas** [comment]
so I am roughing in an app.json and the button now so go ahead and close. The only thing is for it to work, obviously the user has to add the repo url to the generated apps app.json and button in the readme

**Comment by intabulas** [comment]
@keithwhor PR created for heroku stuff so we can close this now
