### ISSUE TITLE
error following video "role does not exist"

### ISSUE THREAD

**Issue by morenoh149** [keithwhor/nodal#47]
running `nodal db:create` on a new machine I got `ERROR: role "postgres" does not exist`

It may be too late to rerecord the video. But the solution is to `createuser postgres -s` to create that role.

solution may be to display example usage of `createuser` in the error message.

**Comment by keithwhor** [comment]
Yep, my initial few passes at recording included this but you also have to install PG command line tools etc... kind of left that out. I'll make sure it's in the README, but "role postgres does not exist" will very quickly direct you to createuser via the Googs, so not sweating it *too* much.

**Comment by keithwhor** [comment]
Going to mark this closed because it's an easily searchable fix, if anybody else has the same issue they'll be able to search for this one. :+1:
