### ISSUE TITLE
Generate db.json when generating app to use app name for database name

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#49]
Right now db.json has a hardcoded `nodal_development` database name. Would be nice to generate the config when running `nodal new` so that the db name could include the app name  vs the default

Optionally prompt during `nodal new` for the db name to allow it to be configured a bit (can prompt have dynamic defaults?

Only issue I see is running doT over a file that uses doT itself.

**Comment by intabulas** [comment]
After pondering dot rendering dot over lunch, if we string-ify (in a file) the production section we can read it in just feed it into a db.json template as a data var and output it

**Comment by keithwhor** [comment]
I don't see *that* much of a problem with doing a `doT.template()` twice on a file. A little bit convoluted, but as long as we document it should be ok.

**Comment by intabulas** [comment]
well its rendering a dot template using dot..

so (as an example).. in a single template eval both {{= }} to get the app name into the db name  and generate doT output  at the same time.. ie: the {{= env.DB...}} stuff in production

**Comment by intabulas** [comment]
looks like a doT inline sub-template will work

**Comment by keithwhor** [comment]
:+1:

**Comment by intabulas** [comment]
didnt work, still tried to evaluate.. The working version I have now has a template json that is parsed, name replaced and generated into the app directory
