### ISSUE TITLE
Allow for optional callback in cli db commands vs straight process.exit

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#50]
While working on #43 / #36 the postdeploy in the heroku app.json allows for a single script. Depending on the state of the app when the web flow is initiated, there might also be migrations existing (say for someone deploying a sample app).

In this case having a super command, lets call it db:bootstrap, that would call both db:prepare and db:migrate inside maybe a async.series would be very helpful.  Right now db commands have `process.exit(0)` in them. 

This issue proposes we add an optional callback param to the db functions that would if excited would be called *instead* of `process.exit(0)` so that the next call in the series would fire. This also means we will need to arg and flags to all methods for consistency. 

Needs more thought, but its the shell of the idea

**Comment by keithwhor** [comment]
I like the idea, if you can mock up what it might look like we can figure out how to rewrite the CLI (it's long overdue anyway).

**Comment by intabulas** [comment]
@keithwhor implemented in a branch in my fork (no pr created yet). Right now it just add the callback support to prepare and migrate and adds a bootstrap command to run both of them.  

You can see it here  https://github.com/intabulas/nodal/commit/70e9e12687d64bc24f044caca4e83cb1091d0fed

**Comment by intabulas** [comment]
I want to cleanup some of the undefined === callback copy pasta before I make it a pr
