### ISSUE TITLE
cli help

### ISSUE THREAD

**Issue by fuzzthink** [keithwhor/nodal#51]
nodal cli doesn't seem to have a help guide.
Please add.

**Comment by keithwhor** [comment]
Will queue this up.

**Comment by intabulas** [comment]
@keithwhor  shall we open a new issue for the cli work, and including your comments in #50 ?

**Comment by keithwhor** [comment]
S'all good. Does now. :+1: Marking this closed, will be refactoring and adding more commands in the future.
