### ISSUE TITLE
Is there a module to entry data?

### ISSUE THREAD

**Issue by hguillermo** [keithwhor/nodal#58]
I am setting up a API server with Nodal. Do you have a module or so to entry data that uses the API generated in Nodal?

**Comment by keithwhor** [comment]
Yep.

https://github.com/keithwhor/APIConnect

As for usage;

```javascript
var API = new APIConnect('http://myserver.com/api/v1');
API.request('users').index(params, function(err, response) { /* */ });
API.request('users').create(params, function(err, response) { /* */ });
API.request('users').show(id, params, function(err, response) { /* */ });
API.request('users').update(id, params, function(err, response) { /* */ });
API.request('users').destroy(id, params, function(err, response) { /* */ });
```

**Comment by hguillermo** [comment]
Sorry I wasn't clear. That is great but I was also looking for a module that offers a UI to enter data. I can build it but I was trying to save some time. I have a few tables that I want to populate. I hope you know something if not no worries. Thanks

**Comment by kitze** [comment]
I wanted this too. Generating some simple ui (with bootstrap) according to the DB models would be really really great! Using postman or a postgres tool to populate the database with sample data isn't really easy/fun :disappointed:

**Comment by keithwhor** [comment]
I think we need some sort of `db:seed` command, @intabulas talked about this. If somebody wants to build a NodalAdmin UI or something of the sort, that's a whole giant project in and of itself. For now there should just be a really easy way to generate sample data.

**Comment by intabulas** [comment]
@keithwhor yeah I am going to open an issue for seeds and use it for a conversation around possible ways to implement

**Comment by intabulas** [comment]
@kitze are you looking for some sort of magical out of the box crud admin ui (ala old school rails scaffold). I like that idea

**Comment by keithwhor** [comment]
I like that idea, but as a separate open source project. `npm install nodal-admin` or something.

**Comment by intabulas** [comment]
@keithwhor yeah its probably better as a separate app, but would have been so easy to use an existing apps schema.json and db.json to do it magically :)

**Comment by keithwhor** [comment]
Going to solve this with: https://github.com/keithwhor/nodal/issues/61
