### ISSUE TITLE
Error when running 'nodal s' using node 4.0.0

### ISSUE THREAD

**Issue by mattiasewers** [keithwhor/nodal#6]
/nodal_test/app/init.js:25
  app.initialize(function() {
      ^

TypeError: app.initialize is not a function

**Comment by keithwhor** [comment]
Are you using the most recent version of Nodal? There are breaking changes from 0.2.x and 0.3.x, and it seems like you're using 0.2.x.

```
app.initialize(...)
```

has been replaced by

```
daemon.start(...)
```

among other things. I can give you a quick overview of what you need to change if this is the case.

**Comment by keithwhor** [comment]
Also, if you have an old version of Nodal installed, make sure you uninstall and run `npm install nodal -g` again.

**Comment by mattiasewers** [comment]
Hmm did that, but can only install 2.3 oddly enough.

**Comment by keithwhor** [comment]
`npm update nodal -g`?

**Comment by mattiasewers** [comment]
I force updated and now it works, thanks!

**Comment by keithwhor** [comment]
No problem :)
