### ISSUE TITLE
Replace native dependency `bcrypt` with `bcryptjs`

### ISSUE THREAD

**Issue by schahriar** [keithwhor/nodal#62]
Native dependency `bcrypt` is a native (C++) module that requires node-gyp and python to build and could be replaced with a pure JS version. I am a fan of native modules myself but I don't believe using them in projects like this is appropriate especially when an excellent alternative such as [bcyptjs](https://www.npmjs.com/package/bcryptjs) exists. Although `bcryptjs` does not perform as fast as C++ version (2.7x slower which isn't too bad for a JS implementation) It would be ideal to use `bcryptjs` as a dependency to make the installation process easier and more friendly to NodeJS newcomers at a cost which is reasonable. I've been using `bcryptjs` in production and have only noticed small delays in logins during load times which is nothing truly significant. Also `bcryptjs` is a drop-in replacement.

Note that the native version of the addon can still be used if we depend on the pure JS version. A user can install `bcrypt` globally and we can check if it is possible to require it (although I personally believe this is not an ideal method yet not an anti-pattern).

If you are open to this I can create a PR.

**Comment by keithwhor** [comment]
Sure. Create the PR. bcrypt is not in nodal by default, only installed when the User model is generated. So I don't think this is a huge issue.

Doesn't matter too much that it's 2.7x slower to me, as long as it doesn't halt the main thread. :)

**Comment by schahriar** [comment]
It is kind of patched async. [Checkout the code here](https://github.com/dcodeIO/bcrypt.js/blob/master/src/bcrypt.js#L112). It uses setImmediate to push the sync function at the back stack so it will let whatever I/O is queued to finish before execution but it will still block the thread while it is running (I doubt native `bcrypt` does something different). You sacrifice a 2.7x slowdown for ease of use and perhaps later we can push the bcrypt process to another thread by spawning a single worker to just do hashing. Let me know if this is good enough to be considered.

**Comment by keithwhor** [comment]
... not the biggest fan of that implementation, then. bcrypt is slow by design and you introduce a really easy DOS target for any service running Nodal. Considering bcrypt is in another package altogether and not part of Nodal's core, it's overhead I'd rather not worry about at this point in time.

**Comment by schahriar** [comment]
that's a good point. I agree with you on that.
