### ISSUE TITLE
CLI Refactoring

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#64]
I am opening this ticket as a place for discussion around refactoring the CLI portions of nodal based in part on @keithwhor comment in #50

While there are issue for smaller fixes now (like #50) this is to share and discuss direction and decisions on how a CLI refresh she be acomplished. 

cc: @schahriar

**Comment by schahriar** [comment]
I propose the following structures for the CLI command organization:

*Option 1*
```javascript
let CommandDefinitions = {
    "<command-name> <arg1> <arg2> ... --<optional-tag>": {
          description: "What the command does",
          category: "Cat 1",
          exec: FUNC_VAR
     },
     ...
}
```
We can parse the command and args to prettify the display and parse and store an array of all categories to display them nicely under their specific category. **This options requires a new definition per possible arguments and tags** which might get out of hand but in my opinion is the most human readable method and the easiest to write.

*Option 2*
```javascript
let CommandDefinitions = {
    "<command-name>": {
          description: "What the command does",
          arguments: {
              "arg1": "What the arg does",
          },
          tags: {
              "tag1": "What the tag does",
               ...
          },
          category: "Cat 1",
          exec: FUNC_VAR
     },
     ...
}
```
This uses a bit more work on writing and reading on both sides but may be appealing to some as it allows for the CommandDefinitions to have less keys overall (although lots of nested keys).

It comes down to flat (option 1) or nested (option 2). I am open to any other solution or improvements on top of this.

**Comment by schahriar** [comment]
Newly proposed model after a discussion with @keithwhor to make it more appropriate to the Nodal style. We can use a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) to store Command classes.

```javascript
// This would be in our CLI.js
let someSet = new Set();

class Command {
  constructor(name, options, fn, desc) {
    this._name = name;
    this._options = options;
    this._desc = desc;
    this._fn = fn;
    someSet.add(this);
   }

  exec(args, flags, callback) {
    this._fn(args, flags, callback);
  }
}

// Pass the Class definition directly to module.exports
require('somefile.js')(Command);
// Another version is to recursively include all subfiles in a directory
```
```javascript
// Some file
module.exports = function(Command){
    // Use inheritance or folder name to introduce prefixes e.g. `db`, `tasks`
    new Command("new", { args: [list of args], flags: [list of flags] }, (args, flags, callback) => {
         ...
    }, "Creates a new Nodal project");
}
```

**Comment by schahriar** [comment]
This is the first change I am making to the CLI https://github.com/schahriar/nodal/commit/f90e0b333feb80c6d5b880aa8e0ed3a0004e8ab7. (moved two folders under a new `interface` folder) By separating the general interface from command-line interface we can allow for future modularity and keep the CLI code truly command-line.

**Comment by schahriar** [comment]
Take note of the following changes:
- `process.exit(x)` is handled by CLI.js internally and Commands instead have a callback that they can call when they are done which handles `process.exit(x)` based on the passed error to the callback.
- Don't log errors straight to the console. Instead use `callback(new Error("Some error"))` CLI will then internally handle how this is displayed.

**Comment by schahriar** [comment]
Basic CLI structure is implemented here https://github.com/schahriar/nodal/commit/b452d3a21f44f3a94801d748b856331b1dde0508

#### How to use it
Create a new js file in `cli/commands`. Create a new command from the passed `Command` class to the `module.exports`. `Command` constructor arguments are ({String} name, {Object} options, {Function} callback)
```javascript
module.exports = function(Command) {
  new Command("s", null, (args, flags, callback) => {
    ... do something ...
    callback();
    // or
    // callback(new Error("some Error"));
  }, "Start the Nodal server based on the current project");
};
```
This will automatically add the command to the CLI & help function, etc. If you want the command to be hidden you can pass `{ hidden: true }` to options (not yet implemented).

##### Extended Classes (soon)

**Comment by intabulas** [comment]
@schahriar up to speed on changes.. One question  (I am curious) is why interface is a tld in the project vs inside of cli

**Comment by schahriar** [comment]
@intabulas just to clarify, it doesn't have to be tld and it's probably more appropriate under `core` folder but don't move it now. It will break a whole bunch of things.

We need to do something about all the relative paths in generators (not sure what file I had issues with) relying on `__dirname` is problematic when you restructure. I suggest defining a global variable and have the root path (usually __dirname + something) in there. Something like this:
```javascript
const path = require("path");
...
let rootPath = "path to root directory";
...
let somePath = path.resolve(rootPath, "./core/...");
```

**Comment by intabulas** [comment]
yeah I fixed a few paths as db:migrate and one other command didn't work.. 

Also all the g: stuff is obviously not wired up yet I noticed

**Comment by intabulas** [comment]
for tracking purposes: dependent task implementation (ie: bootstrap) in a separate branch for discussion..

https://github.com/schahriar/nodal/commit/6cae84091d97d7845a0ffaf3df76a189a29611c9

**Comment by schahriar** [comment]
I will fix `g:` after I get breakfast.

**Comment by schahriar** [comment]
@intabulas added commands for generators here https://github.com/schahriar/nodal/commit/11ee7c958658d0a54030651118381e81e7288740
