### ISSUE TITLE
Invalid select generation after 83222e68

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#67]
I noticed while working on #50  that db:migrate was broken in master.. Roots to the changes you made in 83222e68  adding .update() to composer

it generates the query for migrations as

`SELECT ("schema_migrations"."id") AS "id" FROM (null) AS "schema_migrations"`  since subQuery is null in the migrate command.

I will work on a fix since its blocking #50

**Comment by keithwhor** [comment]
Fixed in https://github.com/keithwhor/nodal/commit/5de80bfa39ebbc902dd7a63a72a15a3b2e2cf692
