### ISSUE TITLE
Nodal on Windows: unresponsive on initialize

### ISSUE THREAD

**Issue by schahriar** [keithwhor/nodal#70]
Nodal `new` command doesn't seem to complete on Powershell (Windows 10) and instead gets stuck at   `Copying Nodal directory structure and files...` although the work around is to use `Ctrl+c` after a few seconds to unpause Nodal but this sometimes skips `Installing packages in this directory...` altogether.

Loosely related to https://github.com/keithwhor/nodal/issues/22 https://github.com/keithwhor/nodal/pull/53.
Should be reviewed at https://github.com/keithwhor/nodal/issues/64

**Comment by keithwhor** [comment]
Might just switch from `ncp` to `fs-extra` for the copy. See if it works better.

**Comment by schahriar** [comment]
I've worked with `fs-extra` before and it does wonders but not sure if it works great on OS X (maybe we could enable OS X testing on Travis?). Since this is a part of the CLI I could take care of it in our whole CLI Refactoring.

**Comment by keithwhor** [comment]
`fs-extra` is fine on OS X in my experience.

**Comment by schahriar** [comment]
So do you plan to do it yourself or let it be a part of the refactoring?

**Comment by keithwhor** [comment]
We can just include it in the refactoring. :)

**Comment by schahriar** [comment]
@keithwhor `fs-extra` fixed this issue but I suggest that you close it after we merge the refactoring.
