### ISSUE TITLE
Meaningful errors

### ISSUE THREAD

**Issue by schahriar** [keithwhor/nodal#71]
Currently Nodal can throw meaningless errors such as `ECONNRESET` or at best `ERROR: password authentication failed for user "postgres"`. These errors should be replaced with more meaningful errors such as
- `Failed to connect to the database. Make sure you have installed and configured PostgreDB`
- `Failed to authenticate for user "postgres". Make sure you have configured your database settings at "./config/db.json".`

**Comment by dandee** [comment]
I have another one:

`DROP SCHEMA public CASCADE
[]

Database Error: must be owner of schema public`

And I have no idea whom should be owner and how to fix that :(

**Comment by keithwhor** [comment]
Archiving. We will always strive to have errors be as communicative as possible, but it's an ongoing process. Use the [gitter channel](http://gitter.im/keithwhor/nodal) to ask questions of the community. :)
