### ISSUE TITLE
Nodal on Windows: skips author on new

### ISSUE THREAD

**Issue by schahriar** [keithwhor/nodal#73]
Windows specific issue. Author is skipped when calling `nodal new`. Perhaps we should use a cross-platform stdin module.

Should be worked on at https://github.com/keithwhor/nodal/issues/64

**Comment by intabulas** [comment]
Looks like a know prompt issue on Win 10.  https://github.com/flatiron/prompt/issues/132

**Comment by schahriar** [comment]
@intabulas thanks for the reference. Will close it for now.

**Comment by schahriar** [comment]
Reopening since it will most likely be fixed after CLI refactor is merged.
