### ISSUE TITLE
Replace the prompt module with inquirer

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#76]
ref: https://github.com/SBoudrias/Inquirer.js

This issue tracks a low impact/risk task to replace the existing use of the flatiron prompt module with inquirer. Prompt is only used (currently) in `nodal new` to prompt users. One of its drawback is lack of access to previous answers in following questions, so doing thing like defaulting a database name to the entered app name is not achievable. Its also has not been updated in over a year and given nodejitsu's acquisition by godaddy who knows if the flatiron stuff will be maintained.

Inquirer allows us to define prompt defaults as functions an thus get at previous anwers. It only contains a collection of nice console inputs (check boxes, select list, etc) that in the future would provide useful. An example of that would be picking the db adapter (when we get more adapters) to use

cc: @schahriar

**Comment by keithwhor** [comment]
:+1: Seems fine to me.

**Comment by intabulas** [comment]
implemented in @schahriar cli refactor fork/brach

https://github.com/schahriar/nodal/commit/c610995cbf51d113412696a7e93655ba96494846

@keithwhor I guess you can close this, or we can wait till is sucked in with the cli work

**Comment by keithwhor** [comment]
Wait til we merge the PR
