### ISSUE TITLE
Declare foregin keys in migration

### ISSUE THREAD

**Issue by sslash** [keithwhor/nodal#80]
How do you declare foreign keys from one model to another with the migrations framework?

**Comment by intabulas** [comment]
How would you like to see this done? Do you want a this.addForeignKey() on the adapter that you can add to a migration manually or are you wanting additions to createTable and add/alter column to specify a simple FK relationship

Would you also be okay if the constraints were inferred by model name automatically?  

ex: (thinking outloud)

```javascript
this.addForeignKey("tweets", "users") 
```
generates

```sql
ALTER TABLE `tweets` ADD CONSTRAINT `tweets_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
```

**Comment by sslash** [comment]
Yeah that looks nice. Or the way node-db-migrate does it. As with here where we specify a type field, you can also have a foreignKey field in the migrations file, e.g:
```
type: 'int',
foreignKey: {
          name: 'product_variant_product_id_fk',
          table: 'product',
          rules: {
            onDelete: 'CASCADE',
            onUpdate: 'RESTRICT'
          },
          mapping: 'id'
        }```

**Comment by intabulas** [comment]
so I pushed to my fork a branch I have been poking at off and on that adds basic simple fk support. It simply adds addForeignKey and dropForeignKey support to migration. It *does not* dump the constraints to the schema or support defining the fk on a createTable.

I haven't created a PR yet, but it has tests that pass.. @keithwhor I was doing this for porting a side project. If your okay with the simple implementation I can make a pr.. It does rely on inflection pkg to singularize the table name.

https://github.com/intabulas/nodal/commit/c59bf944ca539a147ee140df18405982cdad071b

**Comment by keithwhor** [comment]
So I'm iffy on foreign keys in general. I think the ORM should handle logic like cascading deletes / etc. If devs want that sort of control I don't want to say "no," but it's potentially a very slippery slope.

**Comment by intabulas** [comment]
Agree its a slippery slope and yes you have to be careful especially on model#destroy to remove things in the right way.. I remember FKs causing havoc on cascading delete's in an old rails app

I personally don't use them anymore really (maybe because i do alot of mongodb). But I have been enjoying porting old apps as an exercise when I am having code writers block so I added basic support for fun..  Plus it gave me a good excuse to get cozy with the schema generator

@sslash I don't intend on implementing anything more advanced (ie: wired into createTable)

**Comment by intabulas** [comment]
@keithwhor guess we can close this now that you have merged

**Comment by sslash** [comment]
yup

**Comment by keithwhor** [comment]
:+1: Awesome
