### ISSUE TITLE
Suppert postgres arrays and json datatypes

### ISSUE THREAD

**Issue by sslash** [keithwhor/nodal#81]
Currently it seems this is not supported

**Comment by keithwhor** [comment]
PG arrays are supported completely. JSON data types aren't currently. I'm iffy on maintaining or extending support as it will make building other DB adapters a little more difficult.

**Comment by dandee** [comment]
PG JSON/JSONB support would be a major decision point to me while selecting a framework for my team's next project.

**Comment by intabulas** [comment]
@dandee since you have big requirements regarding jsonb, I would love to hear what some of the specific needs are.  Adding support for the datatype is rather trivial (for postgres), but its how do we want to use it that I want to dig into.. 

As a first pass I am thinking about composer#where supporting nested object  
```javascript
{ column: { jsonkeyhere: value } }
```
So use by a model could be:

```javascript
SomeModel.query()
        .where({ column: { jsonkeyhere: value } })
        .end((err, models) => {
            ....
         });
```


would translate into:
```sql
SELECT * FROM table WHERE column->>'jsonkeyhere' = 'value'
```

Or alternatively if  the value was a bool you could do things like all rows with jsonb column docs that contains a specific key

```javascript
{ column: { jsonkeyhere: true} }
```
that would roughly become
```sql
 SELECT * FROM table WHERE column ? 'jsonkeyhere'
```

What other ways are critical for you?

**Comment by intabulas** [comment]
as a follow up, it might be better to do json column references in a where() like this

```javascript
{ 'jsonbcolumn->dockey': value}
```
the amount of almost copy pasta supporting nested objects vs simple string notation (that can be native to whatever adapter) I think is a negative. ie: `typeof columnName === 'object'`

so in a migration you might

```javascript
this.createIndex("recipes", "contents->name", "gin")
```
becomes

```sql
CREATE INDEX "recipes_contents_name_index" ON "recipes" USING gin ((contents->'name'))
```

@keithwhor thoughts?

**Comment by intabulas** [comment]
follow along via https://github.com/intabulas/nodal/commits/JSONB

**Comment by intabulas** [comment]
so create/update support work in the branch.. update allows for partial updates.. I

```javascript
let record = { name: "Pie", contents: { prepTime: "1hr", name: "shells", serves: 17}}

Recipe.create(record, (err, model) => {
  callback();
});
```

```javascript
let record = { contents: { paleo: false}}

Recipe.update(1, record, (err, model) => {
  callback();
});
```

**NOTE:** I might rollback partial updates, kind of  makes it impossible to remove a key

**Comment by keithwhor** [comment]
@intabulas Think the easiest way for querying is to add a special comparator for searching json. Like;

```javascript
.where({column__jsonmatch: {prop: 'value'}})
```

PG arrays definitely supported. No comparators specifically for them though

**Comment by intabulas** [comment]
@keithwhor that would work

**Comment by intabulas** [comment]
@keithwhor so thoughts are partial updates for JSON. I implemented them but it makes deleting a key in a doc impossible (just an Object.assign behind the scenes).. I am thinking I should back it out and require the full doc on an update()

**Comment by intabulas** [comment]
as an update the current plan thats in progress for jsonb and where()  clauses is `where(column__json: { jsonkey: value})` or for cotains queries `where(column__jsoncontains: jsonkey})`

**Comment by dandee** [comment]
@intabulas thanks for your consideration and the quick reply, I appreciate that. So, yes, simple comparison and existence queries cover most of my needs, a nice addition would be containment query ("@>", 8.14.3 http://www.postgresql.org/docs/current/static/datatype-json.html ). As for partial updates allowing to call DB functions would work just fine (for PG 9.4 I would use simple shims in the form like these: https://gist.github.com/inindev/2219dff96851928c2282 ).

**Comment by intabulas** [comment]
@dandee no problem.. I am about to push a PR for comparison (multi-key) and existence support.

**Comment by intabulas** [comment]
@dandee So the first round of JSONB is pushed and in master, would really love your feedback. Would love for you to see if it suits your needs

**Comment by dandee** [comment]
Yes, this looks really promising. In the next couple of days I'm going to put more thorough tests to see how it behaves in more scenarios. Thanks!

**Comment by itajenglish** [comment]
@intabulas  I have an issue where I need to get the value out of a JSONB object key value pair using the query params how would I go about doing this? `http://localhost:3000/v1/group_sessions?location__state__jsoncontains=NY` `state` being the key in the JSONB object.
