### ISSUE TITLE
Add cli command to scaffold empty migration

### ISSUE THREAD

**Issue by justinobney** [keithwhor/nodal#85]
I wanted to add a column to my database through migrations, but I was not able to find any info on accomplishing that task. As a work around, I created a model `nodal g:model foo` with the intention of having the cli generate the file and with a timestamp, and I coded the `up` and `down`.

I would love to see more info on this scenario.

**Comment by keithwhor** [comment]
`nodal g:migration migrationName` should be what you're looking for.

Let me know if that helps, and I'll close the issue. :)

**Comment by keithwhor** [comment]
BTW: Haven't fully documented all of the migration methods. I think that's probably the more important issue here. :)

**Comment by justinobney** [comment]
exactly what I was looking for

**Comment by justinobney** [comment]
Is there any reason not to remove the "hidden" flag here: https://github.com/keithwhor/nodal/blob/master/cli%2Fcommands%2Fg%2Fmigration.js#L10

**Comment by keithwhor** [comment]
We can remove it. :)

**Comment by keithwhor** [comment]
Fixed here:

https://github.com/keithwhor/nodal/commit/5f4701d7d3247262a81f28a63d6bb8b9ec9033bb
