### ISSUE TITLE
Add groupBy to Composer

### ISSUE THREAD

**Issue by intabulas** [keithwhor/nodal#86]
In working on the new example apps, I ran into the need to group results by a column. While the schema generator can generate one, the Composer is missing the ability to add a `GROUP BY` to the query

note: I opened this as a tracking ticket, I am already starting to work on the implementation

**Comment by keithwhor** [comment]
It's in now. :) Basic implementation.

https://github.com/keithwhor/nodal/commit/bbeeaa715da2de0f74b1ecb8a134820582a3111d
