### ISSUE TITLE
Relationships: Finalize definitions + integrate with ORM

### ISSUE THREAD

**Issue by keithwhor** [keithwhor/nodal#9]
Probably want Rails-style support: has_one, belongs_to, has_many. Need final syntax for it. Will have to refactor modules dependent on current structure.

has_one and belongs_to are supported by ORM currently (just in `Model.prototype.relationships`), need to force `.join()` to receive properties.

Should this be the standard behavior? (Always force explicit load of relationships.) Thinking yes. For has_many can just do an `id IN ()` query and assign everything after. (+1 query for every has_many relationship).

**Comment by keithwhor** [comment]
Current iteration:

```
ChildModel.joins(ParentModel); // ParentModel has_one ChildModel
ChildModel.joins(OtherParentModel, {multiple: true}); // OtherParentModel has_many ChildModel
```

Not going to screw around with Rails "has_one", "belongs_to", "has_many" --- though it's easier to read, creates unnecessary complexity (esp. WRT node's import system. With current model definitions you get a cyclical reference if you try to define it both ways.)

All relationships are set bottom-up. Child models must have a reference to their `parent_table_id`, but not vice-versa. Will need to add support for the following:

```
ChildModel.joins(MegaParent, {through: [Parent, SuperParent, UltraParent]});
```

In this case, Parent, SuperParent, and UltraParent should all have their own joins set up (travels up the chain), multiple or not.

Still thinking through siblings (many:many).

**Comment by keithwhor** [comment]
I mean, technically many:many is just:

```
ChildModel.joins(ParentModel);
OtherChildModel.join(ParentModel);
```

Where the Parent is some connector model. Then you'd just need something like.

```
ChildModel.joins(OtherChildModel, {through: [Parent]});
```

You'll have imported both ChildModels, so the references should stay sane. This way you can define any link between two models you want as long as you traverse the dependency chain properly (graph traversal of relationships).

```
ChildModel.join(NthCousinModel, through: [Parent, SuperParent, UltraParent, SuperParentSibling])
```

**Comment by sslash** [comment]
Could you supply a complete example of how many to many works? I'm trying to follow this example, but when I perform the join in the controller, it fails saying ChildModel does not have relationship "parent_model".
