### ISSUE TITLE
DELETES & validation errors

### ISSUE THREAD

**Issue by justinobney** [keithwhor/nodal#90]
When validations are defined on models (Ex: `Opening.validates('location', 'is required', Boolean);`) and a DELETE is called on the entity, the delete succeeds, but the model validation errors are returned as if a POST was being performed.

```js
{
  "meta": {
    "total": 0,
    "count": 0,
    "offset": 0,
    "error": {
      "message": "Validation error",
      "details": {
        "location": [
          "is required"
        ]
      }
    }
  },
  "data": []
}
```

**Comment by keithwhor** [comment]
Thanks for catching this. I have a feeling the model you deleted was missing the location field to begin with, though? Is that the case?

**Comment by justinobney** [comment]
Correct. It was created before a validation


--   Justin Obney
www.justinobney.com

**Comment by keithwhor** [comment]
Alright. Might have to have a skipValidation flag in .respond() then... will get back to you on this.

**Comment by keithwhor** [comment]
Should be fixed with https://github.com/keithwhor/nodal/commit/6badef9c3819e1632c39c06c7a19733072b05227
