### ISSUE TITLE
Nodal Roadmap: Goals for 0.6, 0.7 and path to 1.0

### ISSUE THREAD

**Issue by keithwhor** [keithwhor/nodal#97]
Last updated: **01/13/2016**

### Legend:

:x: Not started
:hourglass: WIP
:white_check_mark: Complete

#### Bugs
- :x: Model#destroy should cascade
- :white_check_mark: ModelArray .destroyAll
- :white_check_mark: ModelArray .saveAll must ensure inherited `save` methods are obeyed (e.g. `User#save`)
- :white_check_mark: Model#destroy should not show validation errors
- :white_check_mark: Model.joinsTo needs to be rethought, or all models need to be `required` on app start

#### Features
- :x: Use environment variables exclusively for app settings
- :x: groupBy for Composer
- :x: Refactor tasks
- :x: Strong parameter support
- :x: Postgres JSON datatype support
- :hourglass: Idiomatic tests in app (using mocha)
- :white_check_mark: Nested template hierarchy (parents w/ children)
- :white_check_mark: Composer `.first()` support
- :white_check_mark: Joining in multiply-nested models

#### Nice-to-haves
- :x: More meaningful errors

#### Features
- :hourglass: WebSocket support
- :hourglass: Clustering of processes (multiple cores, threads)
- :hourglass: Docker integration
- :x: GraphQL Support
- :x: Automatic document generator + formatter for producing docs on [nodaljs.com](http://nodaljs.com)

#### Features
- :hourglass: Comprehensive test suite
- :x: MySQL support

---

### Any and all suggestions welcome!

**Comment by intabulas** [comment]
I might also make this a file in the tld so that its easily discoverable and wont get shuffled down a list of issues

**Comment by abishekrsrikaanth** [comment]
@intabulas  :+1:

**Comment by mkzaker** [comment]
Postgres Geometric datatypes (point,line and polygon) support,please

**Comment by khwerhahn** [comment]
Would love to see updated_at field next to created_at.

**Comment by intabulas** [comment]
PR making this a ROADMAP.md done

**Comment by intabulas** [comment]
@keithwhor I guess we can close this now
