### ISSUE TITLE
No link to website on Github

### ISSUE THREAD

**Issue by robertbenjamin** [keithwhor/nodal#98]
This is a relatively small issue, but it would be nice if there was a link to http://www.nodaljs.com next to the description, in addition to at the bottom of the page under "Documentation".

**Comment by keithwhor** [comment]
Added right under the logo. Thanks for the tip!

**Comment by robertbenjamin** [comment]
That's good too, but why not add it next to the description under the "Website" field? Since it's standard it's where most Github user's eyes jump to when checking out a cool new framework like Nodal.

**Comment by keithwhor** [comment]
I see. :) Totally forgot about that! Thanks again.

**Comment by robertbenjamin** [comment]
:+1: Thanks a lot, loving Nodal and appreciate all the work you put into it!
